#pragma once
 
// This file was generated by Cre3per!s CS:GO dumper on 16.10.2016 - 11:28 CEST
// Counter-Strike Global Offensive/csgo/bin/linux64/client_client.so: ELF 64-bit LSB shared object
//  x86-64
//  version 1 (SYSV)
//  dynamically linked
//  BuildID[sha1]=3664c840d63b10eb2e8bbea5ab0aeb1c551a39c6
//  not stripped
 
 
#include "../SDK/public/mathlib/vector.hpp"
 
using DataTable = int;
 
 
#pragma pack(push, 1)
 
 
class CRagdollPropAttached
{
public:
 
	char __buf_0x00[0x3350]; // 0x0
	QAngle m_attachmentPointBoneSpace; // 0x3350
	char __buf_0x335C[0xC]; // 0x335C
	QAngle m_attachmentPointRagdollSpace; // 0x3368
	int m_ragdollAttachedObjectIndex; // 0x3374
	int m_boneIndexAttached; // 0x3378
 
}; // size=0x337C
 
class CRagdollProp
{
public:
 
	char __buf_0x00[0x3004]; // 0x0
	QAngle m_ragPos; // 0x3004
	char __buf_0x3010[0x114]; // 0x3010
	QAngle m_ragAngles; // 0x3124
	char __buf_0x3130[0x20C]; // 0x3130
	unsigned int m_hUnragdoll; // 0x333C
	float m_flBlendWeight; // 0x3340
	char __buf_0x3344[0x4]; // 0x3344
	int m_nOverlaySequence; // 0x3348
 
}; // size=0x334C
 
class CTEFoundryHelpers
{
public:
 
	int m_iEntity; // 0x20
 
}; // size=0x24
 
class CWorld
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flWaveHeight; // 0xF68
	QAngle m_WorldMins; // 0xF6C
	QAngle m_WorldMaxs; // 0xF78
	int m_bStartDark; // 0xF84
	float m_flMaxOccludeeArea; // 0xF88
	float m_flMinOccluderArea; // 0xF8C
	float m_flMinPropScreenSpaceWidth; // 0xF90
	float m_flMaxPropScreenSpaceWidth; // 0xF94
	int m_bColdWorld; // 0xF98
	int m_iTimeOfDay; // 0xF9C
	char m_iszDetailSpriteMaterial[0x100]; // 0xFA0
 
}; // size=0xFA1
 
class CWaterLODControl
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flCheapWaterStartDistance; // 0xF68
	float m_flCheapWaterEndDistance; // 0xF6C
 
}; // size=0xF70
 
class CVoteController
{
public:
 
	char __buf_0x00[0xF78]; // 0x0
	int m_iActiveIssueIndex; // 0xF78
	int m_iOnlyTeamToVote; // 0xF7C
	DataTable m_nVoteOptionCount; // 0xF80
	char __buf_0xF84[0x14]; // 0xF84
	int m_nPotentialVotes; // 0xF98
	char __buf_0xF9C[0x2]; // 0xF9C
	int m_bIsYesNoVote; // 0xF9E
 
}; // size=0xFA2
 
class CVGuiScreen
{
public:
 
	char __buf_0x00[0xF70]; // 0x0
	float m_flWidth; // 0xF70
	float m_flHeight; // 0xF74
	int m_nPanelName; // 0xF78
	char __buf_0xF7C[0x18]; // 0xF7C
	int m_nAttachmentIndex; // 0xF94
	int m_nOverlayMaterial; // 0xF98
	int m_fScreenFlags; // 0xF9C
	char __buf_0xFA0[0x68]; // 0xFA0
	unsigned long long m_hPlayerOwner; // 0x1008
 
}; // size=0x1010
 
class CPropJeep
{
public:
 
	int m_bHeadlightIsOn; // 0x3180
 
}; // size=0x3184
 
class CPropVehicleChoreoGeneric
{
public:
 
	char __buf_0x00[0x3070]; // 0x0
	unsigned long long m_hPlayer; // 0x3070
	int m_bEnterAnimOn; // 0x3078
	Vector m_vecEyeExitEndpoint; // 0x307C
	int m_bForceEyesToAttachment; // 0x3088
	char __buf_0x308C[0x8C]; // 0x308C
	int m_vehicleView_bClampEyeAngles; // 0x3118
	float m_vehicleView_flPitchCurveZero; // 0x311C
	float m_vehicleView_flPitchCurveLinear; // 0x3120
	float m_vehicleView_flRollCurveZero; // 0x3124
	float m_vehicleView_flRollCurveLinear; // 0x3128
	float m_vehicleView_flFOV; // 0x312C
	float m_vehicleView_flYawMin; // 0x3130
	float m_vehicleView_flYawMax; // 0x3134
	float m_vehicleView_flPitchMin; // 0x3138
	float m_vehicleView_flPitchMax; // 0x313C
 
}; // size=0x3140
 
class CTriggerSoundOperator
{
public:
 
	int m_nSoundOperator; // 0xF94
 
}; // size=0xF98
 
class CBaseTrigger
{
public:
 
	char __buf_0x00[0x314]; // 0x0
	int m_spawnflags; // 0x314
	char __buf_0x318[0xC79]; // 0x318
	int m_bClientSidePredicted; // 0xF91
 
}; // size=0xF95
 
class CTEWorldDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	int m_nIndex; // 0x2C
 
}; // size=0x30
 
class CTESpriteSpray
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecDirection; // 0x2C
	int m_nModelIndex; // 0x38
	int m_nSpeed; // 0x3C
	float m_fNoise; // 0x40
	int m_nCount; // 0x44
 
}; // size=0x48
 
class CTESprite
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	int m_nModelIndex; // 0x2C
	float m_fScale; // 0x30
	int m_nBrightness; // 0x34
 
}; // size=0x38
 
class CTESparks
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	int m_nMagnitude; // 0x2C
	int m_nTrailLength; // 0x30
	Vector m_vecDir; // 0x34
 
}; // size=0x40
 
class CTESmoke
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	int m_nModelIndex; // 0x2C
	float m_fScale; // 0x30
	int m_nFrameRate; // 0x34
 
}; // size=0x38
 
class CTEShowLine
{
public:
 
	Vector m_vecEnd; // 0x2C
 
}; // size=0x38
 
class CTEProjectedDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	QAngle m_angRotation; // 0x2C
	float m_flDistance; // 0x38
	int m_nIndex; // 0x3C
 
}; // size=0x40
 
class CFEPlayerDecal
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_nUniqueID; // 0xF68
	int m_unAccountID; // 0xF6C
	int m_unTraceID; // 0xF70
	int m_rtGcTime; // 0xF74
	Vector m_vecEndPos; // 0xF78
	Vector m_vecStart; // 0xF84
	Vector m_vecRight; // 0xF90
	Vector m_vecNormal; // 0xF9C
	int m_nPlayer; // 0xFA8
	int m_nEntity; // 0xFAC
	int m_nHitbox; // 0xFB0
	int m_nTintID; // 0xFB4
	float m_flCreationTime; // 0xFB8
	int m_nVersion; // 0xFBC
 
}; // size=0xFC0
 
class CTEPlayerDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	int m_nPlayer; // 0x20
	Vector m_vecOrigin; // 0x24
	Vector m_vecStart; // 0x30
	Vector m_vecRight; // 0x3C
	int m_nEntity; // 0x48
	int m_nHitbox; // 0x4C
 
}; // size=0x50
 
class CTEPhysicsProp
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	QAngle m_angRotation; // 0x2C
	Vector m_vecVelocity; // 0x38
	int m_nModelIndex; // 0x44
	int m_nSkin; // 0x48
	int m_nFlags; // 0x4C
	int m_nEffects; // 0x50
	int m_clrRender; // 0x54
 
}; // size=0x58
 
class CTEParticleSystem
{
public:
 
	Vector m_vecOrigin; // 0x20
 
}; // size=0x2C
 
class CTEMuzzleFlash
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecAngles; // 0x2C
	float m_flScale; // 0x38
	int m_nType; // 0x3C
 
}; // size=0x40
 
class CTELargeFunnel
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	int m_nModelIndex; // 0x2C
	int m_nReversed; // 0x30
 
}; // size=0x34
 
class CTEKillPlayerAttachments
{
public:
 
	int m_nPlayer; // 0x20
 
}; // size=0x24
 
class CTEImpact
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecNormal; // 0x2C
	int m_iType; // 0x38
	int m_ucFlags; // 0x3C
 
}; // size=0x40
 
class CTEGlowSprite
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	int m_nModelIndex; // 0x2C
	float m_fScale; // 0x30
	float m_fLife; // 0x34
	int m_nBrightness; // 0x38
 
}; // size=0x3C
 
class CTEShatterSurface
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecAngles; // 0x2C
	Vector m_vecForce; // 0x38
	Vector m_vecForcePos; // 0x44
	float m_flWidth; // 0x50
	float m_flHeight; // 0x54
	float m_flShardSize; // 0x58
	char __buf_0x5C[0xC]; // 0x5C
	int m_nSurfaceType; // 0x68
	unsigned char m_uchFrontColor; // 0x6C
 
}; // size=0x6D
 
class CTEFootprintDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecDirection; // 0x2C
	char __buf_0x38[0xC]; // 0x38
	int m_nEntity; // 0x44
	int m_nIndex; // 0x48
	int m_chMaterialType; // 0x4C
 
}; // size=0x50
 
class CTEFizz
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	int m_nEntity; // 0x20
	int m_nModelIndex; // 0x24
	int m_nDensity; // 0x28
	int m_nCurrent; // 0x2C
 
}; // size=0x30
 
class CTEExplosion
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	int m_nModelIndex; // 0x2C
	float m_fScale; // 0x30
	int m_nFrameRate; // 0x34
	int m_nFlags; // 0x38
	Vector m_vecNormal; // 0x3C
	int m_chMaterialType; // 0x48
	int m_nRadius; // 0x4C
	int m_nMagnitude; // 0x50
 
}; // size=0x54
 
class CTEEnergySplash
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecPos; // 0x20
	Vector m_vecDir; // 0x2C
	int m_bExplosive; // 0x38
 
}; // size=0x3C
 
class CTEEffectDispatch
{
public:
 
	DataTable m_EffectData; // 0x20
 
}; // size=0x24
 
class CTEDynamicLight
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	float m_fRadius; // 0x2C
	int r; // 0x30
	int g; // 0x34
	int b; // 0x38
	int exponent; // 0x3C
	float m_fTime; // 0x40
	float m_fDecay; // 0x44
 
}; // size=0x48
 
class CTEDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecStart; // 0x2C
	int m_nEntity; // 0x38
	int m_nHitbox; // 0x3C
	int m_nIndex; // 0x40
 
}; // size=0x44
 
class CTEClientProjectile
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecVelocity; // 0x2C
	int m_nModelIndex; // 0x38
	int m_nLifeTime; // 0x3C
	unsigned long long m_hOwner; // 0x40
 
}; // size=0x48
 
class CTEBubbleTrail
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecMins; // 0x20
	Vector m_vecMaxs; // 0x2C
	float m_flWaterZ; // 0x38
	int m_nModelIndex; // 0x3C
	int m_nCount; // 0x40
	float m_fSpeed; // 0x44
 
}; // size=0x48
 
class CTEBubbles
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecMins; // 0x20
	Vector m_vecMaxs; // 0x2C
	float m_fHeight; // 0x38
	int m_nModelIndex; // 0x3C
	int m_nCount; // 0x40
	float m_fSpeed; // 0x44
 
}; // size=0x48
 
class CTEBSPDecal
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	int m_nEntity; // 0x2C
	int m_nIndex; // 0x30
 
}; // size=0x34
 
class CTEBreakModel
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	QAngle m_angRotation; // 0x2C
	Vector m_vecSize; // 0x38
	Vector m_vecVelocity; // 0x44
	int m_nRandomization; // 0x50
	int m_nModelIndex; // 0x54
	int m_nCount; // 0x58
	float m_fTime; // 0x5C
	int m_nFlags; // 0x60
 
}; // size=0x64
 
class CTEBloodStream
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	Vector m_vecDirection; // 0x2C
	int r; // 0x38
	int g; // 0x3C
	int b; // 0x40
	int a; // 0x44
	int m_nAmount; // 0x48
 
}; // size=0x4C
 
class CTEBloodSprite
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecOrigin; // 0x20
	Vector m_vecDirection; // 0x2C
	int r; // 0x38
	int g; // 0x3C
	int b; // 0x40
	int a; // 0x44
	int m_nDropModel; // 0x48
	int m_nSprayModel; // 0x4C
	int m_nSize; // 0x50
 
}; // size=0x54
 
class CTEBeamSpline
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecPoints; // 0x20
	char __buf_0x2C[0xB4]; // 0x2C
	int m_nPoints; // 0xE0
 
}; // size=0xE4
 
class CTEBeamRingPoint
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	Vector m_vecCenter; // 0x5C
	float m_flStartRadius; // 0x68
	float m_flEndRadius; // 0x6C
 
}; // size=0x70
 
class CTEBeamRing
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	int m_nStartEntity; // 0x5C
	int m_nEndEntity; // 0x60
 
}; // size=0x64
 
class CTEBeamPoints
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	Vector m_vecStartPoint; // 0x5C
	Vector m_vecEndPoint; // 0x68
 
}; // size=0x74
 
class CTEBeamLaser
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	int m_nStartEntity; // 0x5C
	int m_nEndEntity; // 0x60
 
}; // size=0x64
 
class CTEBeamFollow
{
public:
 
	int m_iEntIndex; // 0x5C
 
}; // size=0x60
 
class CTEBeamEnts
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	int m_nStartEntity; // 0x5C
	int m_nEndEntity; // 0x60
 
}; // size=0x64
 
class CTEBeamEntPoint
{
public:
 
	char __buf_0x00[0x5C]; // 0x0
	int m_nStartEntity; // 0x5C
	int m_nEndEntity; // 0x60
	Vector m_vecStartPoint; // 0x64
	Vector m_vecEndPoint; // 0x70
 
}; // size=0x7C
 
class CTEBaseBeam
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	int m_nModelIndex; // 0x20
	int m_nHaloIndex; // 0x24
	int m_nStartFrame; // 0x28
	int m_nFrameRate; // 0x2C
	float m_fLife; // 0x30
	float m_fWidth; // 0x34
	float m_fEndWidth; // 0x38
	int m_nFadeLength; // 0x3C
	float m_fAmplitude; // 0x40
	int r; // 0x44
	int g; // 0x48
	int b; // 0x4C
	int a; // 0x50
	int m_nSpeed; // 0x54
	int m_nFlags; // 0x58
 
}; // size=0x5C
 
class CTEMetalSparks
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	Vector m_vecPos; // 0x20
	Vector m_vecDir; // 0x2C
 
}; // size=0x38
 
class CTestTraceline
{
public:
 
	char __buf_0x00[0xA8]; // 0x0
	int m_clrRender; // 0xA8
	char __buf_0xAC[0xB4]; // 0xAC
	QAngle m_angRotation; // 0x160
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
 
}; // size=0x180
 
class CTesla
{
public:
 
	char __buf_0x00[0xF98]; // 0x0
	char m_SoundName[0x40]; // 0xF98
	char m_iszSpriteName[0x100]; // 0xFD8
 
}; // size=0xFD9
 
class CBaseTeamObjectiveResource
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_iTimerToShowInHUD; // 0xF68
	int m_iStopWatchTimer; // 0xF6C
	int m_iNumControlPoints; // 0xF70
	char __buf_0xF74[0x4]; // 0xF74
	int m_bPlayingMiniRounds; // 0xF78
	int m_iUpdateCapHudParity; // 0xF7C
	char __buf_0xF80[0x4]; // 0xF80
	Vector m_vCPPositions; // 0xF84
	char __buf_0xF90[0x54]; // 0xF90
	DataTable m_bCPIsVisible; // 0xFE4
	char __buf_0xFE8[0x4]; // 0xFE8
	DataTable m_flLazyCapPerc; // 0xFEC
	char __buf_0xFF0[0x3C]; // 0xFF0
	DataTable m_iTeamIcons; // 0x102C
	char __buf_0x1030[0xFC]; // 0x1030
	DataTable m_iTeamOverlays; // 0x112C
	char __buf_0x1130[0xFC]; // 0x1130
	DataTable m_iTeamReqCappers; // 0x122C
	char __buf_0x1230[0xFC]; // 0x1230
	DataTable m_flTeamCapTime; // 0x132C
	char __buf_0x1330[0xFC]; // 0x1330
	DataTable m_iPreviousPoints; // 0x142C
	char __buf_0x1430[0x2FC]; // 0x1430
	DataTable m_bTeamCanCap; // 0x172C
	char __buf_0x1730[0x3C]; // 0x1730
	DataTable m_iTeamBaseIcons; // 0x176C
	char __buf_0x1770[0x7C]; // 0x1770
	DataTable m_iBaseControlPoints; // 0x17EC
	char __buf_0x17F0[0x7C]; // 0x17F0
	DataTable m_bInMiniRound; // 0x186C
	char __buf_0x1870[0x4]; // 0x1870
	DataTable m_iWarnOnCap; // 0x1874
	char __buf_0x1878[0x1C]; // 0x1878
	char m_iszWarnSound[0xFF]; // 0x1894
	char __buf_0x1993[0x6F9]; // 0x1993
	DataTable m_flPathDistance; // 0x208C
	char __buf_0x2090[0x1C]; // 0x2090
	DataTable m_iNumTeamMembers; // 0x20AC
	char __buf_0x20B0[0xFC]; // 0x20B0
	DataTable m_iCappingTeam; // 0x21AC
	char __buf_0x21B0[0x1C]; // 0x21B0
	DataTable m_iTeamInZone; // 0x21CC
	char __buf_0x21D0[0x1C]; // 0x21D0
	DataTable m_bBlocked; // 0x21EC
	char __buf_0x21F0[0x4]; // 0x21F0
	DataTable m_iOwner; // 0x21F4
	char __buf_0x21F8[0x84]; // 0x21F8
	char m_pszCapLayoutInHUD[0x20]; // 0x227C
 
}; // size=0x227D
 
class CTeam
{
public:
 
	char __buf_0x00[0xF88]; // 0x0
	char m_szTeamname[0x20]; // 0xF88
	char m_szClanTeamname[0x20]; // 0xFA8
	char m_szTeamFlagImage[0x8]; // 0xFC8
	char m_szTeamLogoImage[0x8]; // 0xFD0
	char m_szTeamMatchStat[0x104]; // 0xFD8
	int m_scoreTotal; // 0x10DC
	int m_scoreFirstHalf; // 0x10E0
	int m_scoreSecondHalf; // 0x10E4
	int m_scoreOvertime; // 0x10E8
	int m_nGGLeaderEntIndex_CT; // 0x10EC
	int m_nGGLeaderEntIndex_T; // 0x10F0
	int m_iClanID; // 0x10F4
	char __buf_0x10F8[0xC]; // 0x10F8
	int m_iTeamNum; // 0x1104
	int m_bSurrendered; // 0x1108
 
}; // size=0x110C
 
class CSunlightShadowControl
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	QAngle m_shadowDirection; // 0xF68
	int m_bEnabled; // 0xF74
	char __buf_0xF78[0x110]; // 0xF78
	int m_LightColor; // 0x1088
	char __buf_0x108C[0x10]; // 0x108C
	float m_flColorTransitionTime; // 0x109C
	float m_flSunDistance; // 0x10A0
	float m_flFOV; // 0x10A4
	float m_flNearZ; // 0x10A8
	float m_flNorthOffset; // 0x10AC
	int m_bEnableShadows; // 0x10B0
 
}; // size=0x10B4
 
class CSun
{
public:
 
	char __buf_0x00[0xA8]; // 0x0
	int m_clrRender; // 0xA8
	char __buf_0xAC[0x105C]; // 0xAC
	int m_clrOverlay; // 0x1108
	int m_nSize; // 0x110C
	int m_nOverlaySize; // 0x1110
	Vector m_vDirection; // 0x1114
	int m_bOn; // 0x1120
	int m_nMaterial; // 0x1124
	int m_nOverlayMaterial; // 0x1128
 
}; // size=0x112C
 
class CSteamJet
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	float m_SpreadSpeed; // 0x10A0
	float m_Speed; // 0x10A4
	float m_StartSize; // 0x10A8
	float m_EndSize; // 0x10AC
	float m_Rate; // 0x10B0
	float m_JetLength; // 0x10B4
	int m_bEmit; // 0x10B8
	int m_nType; // 0x10BC
	int m_bFaceLeft; // 0x10C0
	int m_spawnflags; // 0x10C4
	float m_flRollSpeed; // 0x10C8
 
}; // size=0x10CC
 
class CParticlePerformanceMonitor
{
public:
 
	int m_bDisplayPerf; // 0xF65
 
}; // size=0xF69
 
class CSpotlightEnd
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flLightScale; // 0xF68
	float m_Radius; // 0xF6C
 
}; // size=0xF70
 
class CSpatialEntity
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	Vector m_vecOrigin; // 0xF68
	float m_minFalloff; // 0xF74
	float m_maxFalloff; // 0xF78
	float m_flCurWeight; // 0xF7C
	char __buf_0xF80[0x104]; // 0xF80
	int m_bEnabled; // 0x1084
 
}; // size=0x1088
 
class DustTrail
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	float m_SpawnRate; // 0x10A0
	QAngle m_Color; // 0x10A4
	float m_Opacity; // 0x10B0
	float m_ParticleLifetime; // 0x10B4
	char __buf_0x10B8[0x4]; // 0x10B8
	float m_StopEmitTime; // 0x10BC
	float m_MinSpeed; // 0x10C0
	float m_MaxSpeed; // 0x10C4
	float m_MinDirectedSpeed; // 0x10C8
	float m_MaxDirectedSpeed; // 0x10CC
	float m_StartSize; // 0x10D0
	float m_EndSize; // 0x10D4
	float m_SpawnRadius; // 0x10D8
	char __buf_0x10DC[0xC]; // 0x10DC
	int m_bEmit; // 0x10E8
 
}; // size=0x10EC
 
class CFireTrail
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	int m_nAttachment; // 0x10A0
	float m_flLifetime; // 0x10A4
 
}; // size=0x10A8
 
class SporeTrail
{
public:
 
	char __buf_0x00[0x1098]; // 0x0
	Vector m_vecEndColor; // 0x1098
	float m_flSpawnRate; // 0x10A4
	float m_flParticleLifetime; // 0x10A8
	float m_flStartSize; // 0x10AC
	float m_flEndSize; // 0x10B0
	float m_flSpawnRadius; // 0x10B4
	char __buf_0x10B8[0xC]; // 0x10B8
	int m_bEmit; // 0x10C4
 
}; // size=0x10C8
 
class SporeExplosion
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	float m_flSpawnRate; // 0x10A0
	float m_flParticleLifetime; // 0x10A4
	float m_flStartSize; // 0x10A8
	float m_flEndSize; // 0x10AC
	float m_flSpawnRadius; // 0x10B0
	char __buf_0x10B4[0x4]; // 0x10B4
	int m_bEmit; // 0x10B8
 
}; // size=0x10BC
 
class RocketTrail
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	float m_SpawnRate; // 0x10A0
	QAngle m_StartColor; // 0x10A4
	QAngle m_EndColor; // 0x10B0
	float m_Opacity; // 0x10BC
	float m_ParticleLifetime; // 0x10C0
	float m_StopEmitTime; // 0x10C4
	float m_MinSpeed; // 0x10C8
	float m_MaxSpeed; // 0x10CC
	float m_StartSize; // 0x10D0
	float m_EndSize; // 0x10D4
	float m_SpawnRadius; // 0x10D8
	char __buf_0x10DC[0xC]; // 0x10DC
	int m_bEmit; // 0x10E8
	int m_nAttachment; // 0x10EC
	char __buf_0x10F0[0xC]; // 0x10F0
	float m_flFlareScale; // 0x10FC
 
}; // size=0x1100
 
class SmokeTrail
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	float m_SpawnRate; // 0x10A0
	QAngle m_StartColor; // 0x10A4
	QAngle m_EndColor; // 0x10B0
	float m_Opacity; // 0x10BC
	float m_ParticleLifetime; // 0x10C0
	float m_StopEmitTime; // 0x10C4
	float m_MinSpeed; // 0x10C8
	float m_MaxSpeed; // 0x10CC
	float m_MinDirectedSpeed; // 0x10D0
	float m_MaxDirectedSpeed; // 0x10D4
	float m_StartSize; // 0x10D8
	float m_EndSize; // 0x10DC
	float m_SpawnRadius; // 0x10E0
	char __buf_0x10E4[0xC]; // 0x10E4
	int m_bEmit; // 0x10F0
	int m_nAttachment; // 0x10F4
 
}; // size=0x10F8
 
class CSmokeStack
{
public:
 
	char __buf_0x00[0x10F8]; // 0x0
	float m_SpreadSpeed; // 0x10F8
	float m_Speed; // 0x10FC
	float m_StartSize; // 0x1100
	float m_EndSize; // 0x1104
	float m_Rate; // 0x1108
	float m_JetLength; // 0x110C
	int m_bEmit; // 0x1110
	float m_flBaseSpread; // 0x1114
	QAngle m_AmbientLight_m_vPos; // 0x1118
	QAngle m_AmbientLight_m_vColor; // 0x1124
	float m_AmbientLight_m_flIntensity; // 0x1130
	QAngle m_DirLight_m_vPos; // 0x1134
	QAngle m_DirLight_m_vColor; // 0x1140
	float m_DirLight_m_flIntensity; // 0x114C
	char __buf_0x1150[0xC]; // 0x1150
	Vector m_vWind; // 0x115C
	float m_flTwist; // 0x1168
	int m_iMaterialModel; // 0x116C
	char __buf_0x1170[0x40]; // 0x1170
	float m_flRollSpeed; // 0x11B0
 
}; // size=0x11B4
 
class CSlideshowDisplay
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	int m_bEnabled; // 0xF65
	char __buf_0xF69[0x7D]; // 0xF69
	char m_szSlideshowDirectory[0x80]; // 0xFE6
	char __buf_0x1066[0x22]; // 0x1066
	DataTable m_chCurrentSlideLists; // 0x1088
	char __buf_0x108C[0x14]; // 0x108C
	float m_fMinSlideTime; // 0x10A0
	float m_fMaxSlideTime; // 0x10A4
	char __buf_0x10A8[0x4]; // 0x10A8
	int m_iCycleType; // 0x10AC
	int m_bNoListRepeats; // 0x10B0
 
}; // size=0x10B4
 
class CShadowControl
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	QAngle m_shadowDirection; // 0xF68
	int m_shadowColor; // 0xF74
	float m_flShadowMaxDist; // 0xF78
	int m_bDisableShadows; // 0xF7C
 
}; // size=0xF80
 
class CSceneEntity
{
public:
 
	char __buf_0x00[0xF70]; // 0x0
	unsigned char m_bIsPlayingBack; // 0xF70
	char __buf_0xF71[0x1]; // 0xF71
	int m_bMultiplayer; // 0xF72
	char __buf_0xF76[0x2]; // 0xF76
	float m_flForceClientTime; // 0xF78
	int m_nSceneStringIndex; // 0xF7C
 
}; // size=0xF80
 
class CRopeKeyframe
{
public:
 
	char __buf_0x00[0x16C]; // 0x0
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
	char __buf_0x180[0x1C0]; // 0x180
	int m_iParentAttachment; // 0x340
	char __buf_0x344[0xBD4]; // 0x344
	unsigned char m_nMinCPULevel; // 0xF18
	char __buf_0xF19[0x1]; // 0xF19
	int m_nMinGPULevel; // 0xF1A
	char __buf_0xF1E[0x7E]; // 0xF1E
	float m_flScrollSpeed; // 0xF9C
	int m_RopeFlags; // 0xFA0
	int m_iRopeMaterialModelIndex; // 0xFA4
	int m_iDefaultRopeMaterialModelIndex; // 0xFA8
	char __buf_0xFAC[0x2EC]; // 0xFAC
	int m_nSegments; // 0x1298
	unsigned int m_hStartPoint; // 0x129C
	unsigned int m_hEndPoint; // 0x12A0
	unsigned char m_iStartAttachment; // 0x12A4
	char __buf_0x12A5[0x1]; // 0x12A5
	unsigned char m_iEndAttachment; // 0x12A6
	char __buf_0x12A7[0x1]; // 0x12A7
	int m_Subdiv; // 0x12A8
	int m_RopeLength; // 0x12AC
	int m_Slack; // 0x12B0
	float m_TextureScale; // 0x12B4
	int m_fLockedPoints; // 0x12B8
	int m_nChangeCount; // 0x12BC
	float m_Width; // 0x12C0
	char __buf_0x12C4[0x8C]; // 0x12C4
	int m_bConstrainBetweenEndpoints; // 0x1350
 
}; // size=0x1354
 
class CRagdollManager
{
public:
 
	int m_iCurrentMaxRagdollCount; // 0xF68
 
}; // size=0xF6C
 
class CPropVehicleDriveable
{
public:
 
	char __buf_0x00[0x3010]; // 0x0
	unsigned int m_hPlayer; // 0x3010
	int m_nSpeed; // 0x3014
	int m_nRPM; // 0x3018
	float m_flThrottle; // 0x301C
	int m_nBoostTimeLeft; // 0x3020
	int m_nHasBoost; // 0x3024
	int m_nScannerDisabledWeapons; // 0x3028
	int m_nScannerDisabledVehicle; // 0x302C
	char __buf_0x3030[0x1C]; // 0x3030
	int m_bEnterAnimOn; // 0x304C
	char __buf_0x3050[0x4]; // 0x3050
	Vector m_vecGunCrosshair; // 0x3054
	char __buf_0x3060[0x48]; // 0x3060
	Vector m_vecEyeExitEndpoint; // 0x30A8
	int m_bHasGun; // 0x30B4
 
}; // size=0x30B8
 
class CProp_Hallucination
{
public:
 
	char __buf_0x00[0x3021]; // 0x0
	int m_bEnabled; // 0x3021
	float m_fVisibleTime; // 0x3024
	float m_fRechargeTime; // 0x3028
 
}; // size=0x302C
 
class CPhysicsPropMultiplayer
{
public:
 
	char __buf_0x00[0x3040]; // 0x0
	int m_iPhysicsMode; // 0x3040
	float m_fMass; // 0x3044
	QAngle m_collisionMins; // 0x3048
	QAngle m_collisionMaxs; // 0x3054
 
}; // size=0x3060
 
class CPhysBoxMultiplayer
{
public:
 
	char __buf_0x00[0xF78]; // 0x0
	int m_iPhysicsMode; // 0xF78
	float m_fMass; // 0xF7C
 
}; // size=0xF80
 
class CDynamicProp
{
public:
 
	char __buf_0x00[0x3024]; // 0x0
	int m_bUseHitboxesForRenderBox; // 0x3024
	char __buf_0x3028[0x1C]; // 0x3028
	float m_flGlowMaxDist; // 0x3044
	int m_bShouldGlow; // 0x3048
	char __buf_0x304C[0x4]; // 0x304C
	int m_nGlowStyle; // 0x3050
 
}; // size=0x3054
 
class CPostProcessController
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	DataTable m_flPostProcessParameters; // 0xF68
	char __buf_0xF6C[0x28]; // 0xF6C
	int m_bMaster; // 0xF94
 
}; // size=0xF98
 
class CPointCommentaryNode
{
public:
 
	char __buf_0x00[0x3001]; // 0x0
	int m_bActive; // 0x3001
	float m_flStartTime; // 0x3004
	char m_iszCommentaryFile[0x104]; // 0x3008
	char m_iszCommentaryFileNoHDR[0x104]; // 0x310C
	char m_iszSpeakers[0x100]; // 0x3210
	int m_iNodeNumber; // 0x3310
	int m_iNodeNumberMax; // 0x3314
	char __buf_0x3318[0x8]; // 0x3318
	unsigned long long m_hViewPosition; // 0x3320
 
}; // size=0x3328
 
class CPointCamera
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_FOV; // 0xF68
	float m_Resolution; // 0xF6C
	int m_bFogEnable; // 0xF70
	char __buf_0xF74[0x4]; // 0xF74
	float m_flFogStart; // 0xF78
	float m_flFogEnd; // 0xF7C
	float m_flFogMaxDensity; // 0xF80
	int m_bActive; // 0xF84
 
}; // size=0xF88
 
class CPlayerResource
{
public:
 
	char __buf_0x00[0x1180]; // 0x0
	DataTable m_iPing; // 0x1180
	char __buf_0x1184[0x100]; // 0x1184
	DataTable m_iKills; // 0x1284
	char __buf_0x1288[0x100]; // 0x1288
	DataTable m_iAssists; // 0x1388
	char __buf_0x138C[0x100]; // 0x138C
	DataTable m_iDeaths; // 0x148C
	char __buf_0x1490[0x100]; // 0x1490
	DataTable m_bConnected; // 0x1590
	char __buf_0x1594[0x40]; // 0x1594
	DataTable m_iTeam; // 0x15D4
	char __buf_0x15D8[0x100]; // 0x15D8
	DataTable m_iPendingTeam; // 0x16D8
	char __buf_0x16DC[0x100]; // 0x16DC
	DataTable m_bAlive; // 0x17DC
	char __buf_0x17E0[0x40]; // 0x17E0
	DataTable m_iHealth; // 0x1820
	char __buf_0x1824[0x180]; // 0x1824
	DataTable m_iCoachingTeam; // 0x19A4
 
}; // size=0x19A8
 
class CPlasma
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flStartScale; // 0xF68
	float m_flScale; // 0xF6C
	float m_flScaleTime; // 0xF70
	int m_nFlags; // 0xF74
	int m_nPlasmaModelIndex; // 0xF78
	int m_nPlasmaModelIndex2; // 0xF7C
	int m_nGlowModelIndex; // 0xF80
 
}; // size=0xF84
 
class CStatueProp
{
public:
 
	char __buf_0x00[0x3038]; // 0x0
	unsigned int m_hInitBaseAnimating; // 0x3038
	int m_bShatter; // 0x303C
	int m_nShatterFlags; // 0x3040
	Vector m_vShatterPosition; // 0x3044
	Vector m_vShatterForce; // 0x3050
 
}; // size=0x305C
 
class CPhysicsProp
{
public:
 
	char __buf_0x00[0x314]; // 0x0
	int m_spawnflags; // 0x314
	char __buf_0x318[0x2D05]; // 0x318
	int m_bAwake; // 0x301D
 
}; // size=0x3021
 
class CPhysBox
{
public:
 
	float m_mass; // 0xF68
 
}; // size=0xF6C
 
class CParticleSystem
{
public:
 
	char __buf_0x00[0x124]; // 0x0
	int m_fEffects; // 0x124
	char __buf_0x128[0x38]; // 0x128
	QAngle m_angRotation; // 0x160
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
	unsigned long long m_hOwnerEntity; // 0x180
	char __buf_0x188[0x1B8]; // 0x188
	int m_iParentAttachment; // 0x340
	char __buf_0x344[0xC24]; // 0x344
	int m_iEffectIndex; // 0xF68
	int m_nStopType; // 0xF6C
	int m_bActive; // 0xF70
	float m_flStartTime; // 0xF74
	char m_szSnapshotFileName[0x104]; // 0xF78
	DataTable m_vServerControlPoints; // 0x107C
	char __buf_0x1080[0x2C]; // 0x1080
	DataTable m_iServerControlPointAssignments; // 0x10AC
	char __buf_0x10B0[0x20]; // 0x10B0
	DataTable m_hControlPointEnts; // 0x10D0
	char __buf_0x10D4[0xF8]; // 0x10D4
	DataTable m_iControlPointParents; // 0x11CC
 
}; // size=0x11D0
 
class ParticleSmokeGrenade
{
public:
 
	char __buf_0x00[0x10A0]; // 0x0
	int m_CurrentStage; // 0x10A0
	char __buf_0x10A4[0xC]; // 0x10A4
	float m_flSpawnTime; // 0x10B0
	float m_FadeStartTime; // 0x10B4
	float m_FadeEndTime; // 0x10B8
	char __buf_0x10BC[0x4]; // 0x10BC
	QAngle m_MinColor; // 0x10C0
	QAngle m_MaxColor; // 0x10CC
 
}; // size=0x10D8
 
class CParticleFire
{
public:
 
	char __buf_0x00[0x10B0]; // 0x0
	Vector m_vOrigin; // 0x10B0
	Vector m_vDirection; // 0x10BC
 
}; // size=0x10C8
 
class CMovieDisplay
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	unsigned char m_bEnabled; // 0xF65
	char __buf_0xF66[0x1]; // 0xF66
	char m_szMovieFilename[0x80]; // 0xF67
	char m_szGroupName[0x80]; // 0xFE7
	unsigned char m_bStretchToFill; // 0x1067
	char __buf_0x1068[0x1]; // 0x1068
	int m_bUseCustomUVs; // 0x1069
	float m_flUMin; // 0x106C
	float m_flUMax; // 0x1070
	float m_flVMin; // 0x1074
	float m_flVMax; // 0x1078
 
}; // size=0x107C
 
class CMaterialModifyControl
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	char m_szMaterialName[0xFF]; // 0xF65
	char m_szMaterialVar[0xFF]; // 0x1064
	char m_szMaterialVarValue[0xFF]; // 0x1163
	char __buf_0x1262[0x12]; // 0x1262
	int m_iFrameStart; // 0x1274
	int m_iFrameEnd; // 0x1278
	int m_bWrap; // 0x127C
	float m_flFramerate; // 0x1280
	int m_bNewAnimCommandsSemaphore; // 0x1284
	float m_flFloatLerpStartValue; // 0x1288
	float m_flFloatLerpEndValue; // 0x128C
	float m_flFloatLerpTransitionTime; // 0x1290
	int m_bFloatLerpWrap; // 0x1294
	char __buf_0x1298[0x4]; // 0x1298
	int m_nModifyMode; // 0x129C
 
}; // size=0x12A0
 
class CLightGlow
{
public:
 
	char __buf_0x00[0xA8]; // 0x0
	int m_clrRender; // 0xA8
	char __buf_0xAC[0xB4]; // 0xAC
	QAngle m_angRotation; // 0x160
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
	char __buf_0x180[0xDE8]; // 0x180
	int m_nHorizontalSize; // 0xF68
	int m_nVerticalSize; // 0xF6C
	int m_nMinDist; // 0xF70
	int m_nMaxDist; // 0xF74
	int m_nOuterMaxDist; // 0xF78
	int m_spawnflags; // 0xF7C
	char __buf_0xF80[0xF8]; // 0xF80
	float m_flGlowProxySize; // 0x1078
 
}; // size=0x107C
 
class CInfoOverlayAccessor
{
public:
 
	char __buf_0x00[0xF1C]; // 0x0
	int m_iTextureFrameIndex; // 0xF1C
	char __buf_0xF20[0x48]; // 0xF20
	int m_iOverlayID; // 0xF68
 
}; // size=0xF6C
 
class CTEGaussExplosion
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	int m_nType; // 0x2C
	Vector m_vecDirection; // 0x30
 
}; // size=0x3C
 
class CFuncSmokeVolume
{
public:
 
	char __buf_0x00[0x378]; // 0x0
	unsigned long long m_Collision; // 0x378
	char __buf_0x380[0xD20]; // 0x380
	int m_Color1; // 0x10A0
	int m_Color2; // 0x10A4
	char m_MaterialName[0xFF]; // 0x10A8
	char __buf_0x11A7[0x1]; // 0x11A7
	float m_ParticleDrawWidth; // 0x11A8
	float m_ParticleSpacingDistance; // 0x11AC
	float m_DensityRampSpeed; // 0x11B0
	float m_RotationSpeed; // 0x11B4
	float m_MovementSpeed; // 0x11B8
	float m_Density; // 0x11BC
	float m_maxDrawDistance; // 0x11C0
	int m_spawnflags; // 0x11C4
 
}; // size=0x11C8
 
class CFuncRotating
{
public:
 
	char __buf_0x00[0x160]; // 0x0
	QAngle m_angRotation; // 0x160
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x124]; // 0x178
	int m_flSimulationTime; // 0x29C
 
}; // size=0x2A0
 
class CFuncOccluder
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_nOccluderIndex; // 0xF68
	int m_bActive; // 0xF6C
 
}; // size=0xF70
 
class CFuncMoveLinear
{
public:
 
	char __buf_0x00[0x138]; // 0x0
	int m_fFlags; // 0x138
	char __buf_0x13C[0xC]; // 0x13C
	Vector m_vecVelocity; // 0x148
 
}; // size=0x154
 
class CFunc_LOD
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_nDisappearMinDist; // 0xF68
	int m_nDisappearMaxDist; // 0xF6C
 
}; // size=0xF70
 
class CTEDust
{
public:
 
	char __buf_0x00[0x2C]; // 0x0
	float m_flSize; // 0x2C
	float m_flSpeed; // 0x30
	Vector m_vecDirection; // 0x34
 
}; // size=0x40
 
class CFunc_Dust
{
public:
 
	char __buf_0x00[0x28C]; // 0x0
	int m_nModelIndex; // 0x28C
	char __buf_0x290[0xE8]; // 0x290
	unsigned long long m_Collision; // 0x378
	char __buf_0x380[0xBE5]; // 0x380
	int m_Color; // 0xF65
	char __buf_0xF69[0x3]; // 0xF69
	int m_SpawnRate; // 0xF6C
	float m_flSizeMin; // 0xF70
	float m_flSizeMax; // 0xF74
	int m_SpeedMax; // 0xF78
	int m_LifetimeMin; // 0xF7C
	int m_LifetimeMax; // 0xF80
	int m_DistMax; // 0xF84
	float m_FallSpeed; // 0xF88
	int m_bAffectedByWind; // 0xF8C
	int m_DustFlags; // 0xF90
 
}; // size=0xF94
 
class CFuncConveyor
{
public:
 
	float m_flConveyorSpeed; // 0xF68
 
}; // size=0xF6C
 
class CBreakableSurface
{
public:
 
	char __buf_0x00[0xF70]; // 0x0
	int m_nNumWide; // 0xF70
	int m_nNumHigh; // 0xF74
	float m_flPanelWidth; // 0xF78
	float m_flPanelHeight; // 0xF7C
	Vector m_vNormal; // 0xF80
	Vector m_vCorner; // 0xF8C
	int m_bIsBroken; // 0xF98
	int m_nSurfaceType; // 0xF9C
	char __buf_0xFA0[0x30]; // 0xFA0
	DataTable m_RawPanelBitVec; // 0xFD0
 
}; // size=0xFD4
 
class CFuncAreaPortalWindow
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flFadeStartDist; // 0xF68
	float m_flFadeDist; // 0xF6C
	float m_flTranslucencyLimit; // 0xF70
	int m_iBackgroundModelIndex; // 0xF74
 
}; // size=0xF78
 
class CFish
{
public:
 
	char __buf_0x00[0x28C]; // 0x0
	int m_nModelIndex; // 0x28C
	char __buf_0x290[0x3]; // 0x290
	int m_lifeState; // 0x293
	char __buf_0x297[0x2DB9]; // 0x297
	float m_x; // 0x3050
	float m_y; // 0x3054
	float m_z; // 0x3058
	char __buf_0x305C[0x4]; // 0x305C
	float m_angle; // 0x3060
	char __buf_0x3064[0x4]; // 0x3064
	QAngle m_poolOrigin; // 0x3068
	float m_waterLevel; // 0x3074
 
}; // size=0x3078
 
class CFireSmoke
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flStartScale; // 0xF68
	float m_flScale; // 0xF6C
	float m_flScaleTime; // 0xF70
	int m_nFlags; // 0xF74
	int m_nFlameModelIndex; // 0xF78
	int m_nFlameFromAboveModelIndex; // 0xF7C
 
}; // size=0xF80
 
class CEnvTonemapController
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	unsigned char m_bUseCustomAutoExposureMin; // 0xF65
	char __buf_0xF66[0x1]; // 0xF66
	int m_bUseCustomBloomScale; // 0xF67
	char __buf_0xF6B[0x1]; // 0xF6B
	float m_flCustomAutoExposureMax; // 0xF6C
	float m_flCustomBloomScale; // 0xF70
	float m_flCustomBloomScaleMinimum; // 0xF74
	float m_flBloomExponent; // 0xF78
	float m_flBloomSaturation; // 0xF7C
	float m_flTonemapPercentTarget; // 0xF80
	float m_flTonemapPercentBrightPixels; // 0xF84
	float m_flTonemapMinAvgLum; // 0xF88
	float m_flTonemapRate; // 0xF8C
 
}; // size=0xF90
 
class CEnvScreenEffect
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flDuration; // 0xF68
	int m_nType; // 0xF6C
 
}; // size=0xF70
 
class CEnvScreenOverlay
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	char m_iszOverlayNames[0xFF]; // 0xF65
	char __buf_0x1064[0x8F8]; // 0x1064
	QAngle m_flOverlayTimes; // 0x195C
	char __buf_0x1968[0x1C]; // 0x1968
	float m_flStartTime; // 0x1984
	int m_iDesiredOverlay; // 0x1988
	int m_bIsActive; // 0x198C
 
}; // size=0x1990
 
class CEnvProjectedTexture
{
public:
 
	char __buf_0x00[0xF6C]; // 0x0
	unsigned int m_hTargetEntity; // 0xF6C
	int m_bState; // 0xF70
	float m_flLightFOV; // 0xF74
	unsigned char m_bEnableShadows; // 0xF78
	char __buf_0xF79[0x1]; // 0xF79
	unsigned char m_bLightOnlyTarget; // 0xF7A
	char __buf_0xF7B[0x1]; // 0xF7B
	int m_bCameraSpace; // 0xF7C
	float m_flBrightnessScale; // 0xF80
	int m_LightColor; // 0xF84
	char __buf_0xF88[0x10]; // 0xF88
	float m_flColorTransitionTime; // 0xF98
	float m_flAmbient; // 0xF9C
	float m_flNearZ; // 0xFA0
	float m_flFarZ; // 0xFA4
	char m_SpotlightTextureName[0x104]; // 0xFA8
	char __buf_0x10AC[0x14]; // 0x10AC
	int m_nSpotlightTextureFrame; // 0x10C0
	int m_nShadowQuality; // 0x10C4
	int m_iStyle; // 0x10C8
	char __buf_0x10CC[0xC]; // 0x10CC
	float m_flProjectionSize; // 0x10D8
	float m_flRotation; // 0x10DC
 
}; // size=0x10E0
 
class CEnvParticleScript
{
public:
 
	float m_flSequenceScale; // 0x3138
 
}; // size=0x313C
 
class CFogController
{
public:
 
	char __buf_0x00[0xF70]; // 0x0
	QAngle m_fog_dirPrimary; // 0xF70
	int m_fog_colorPrimary; // 0xF7C
	int m_fog_colorSecondary; // 0xF80
	int m_fog_colorPrimaryLerpTo; // 0xF84
	int m_fog_colorSecondaryLerpTo; // 0xF88
	float m_fog_start; // 0xF8C
	float m_fog_end; // 0xF90
	float m_fog_farz; // 0xF94
	float m_fog_maxdensity; // 0xF98
	float m_fog_startLerpTo; // 0xF9C
	float m_fog_endLerpTo; // 0xFA0
	float m_fog_maxdensityLerpTo; // 0xFA4
	float m_fog_lerptime; // 0xFA8
	float m_fog_duration; // 0xFAC
	int m_fog_enable; // 0xFB0
	float m_fog_ZoomFogScale; // 0xFB4
	float m_fog_HDRColorScale; // 0xFB8
 
}; // size=0xFBC
 
class CEnvDOFController
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	int m_bDOFEnabled; // 0xF65
	float m_flNearBlurDepth; // 0xF68
	float m_flNearFocusDepth; // 0xF6C
	float m_flFarFocusDepth; // 0xF70
	float m_flFarBlurDepth; // 0xF74
	float m_flNearBlurRadius; // 0xF78
	float m_flFarBlurRadius; // 0xF7C
 
}; // size=0xF80
 
class CCascadeLight
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	QAngle m_shadowDirection; // 0xF68
	QAngle m_envLightShadowDirection; // 0xF74
	unsigned char m_bEnabled; // 0xF80
	char __buf_0xF81[0x1]; // 0xF81
	int m_LightColor; // 0xF82
	char __buf_0xF86[0x2]; // 0xF86
	int m_LightColorScale; // 0xF88
	float m_flMaxShadowDist; // 0xF8C
 
}; // size=0xF90
 
class CEnvAmbientLight
{
public:
 
	Vector m_vecColor; // 0x1090
 
}; // size=0x109C
 
class CEntityParticleTrail
{
public:
 
	char __buf_0x00[0x1098]; // 0x0
	int m_iMaterialName; // 0x1098
	char __buf_0x109C[0x4]; // 0x109C
	DataTable m_Info; // 0x10A0
	char __buf_0x10A4[0x1C]; // 0x10A4
	unsigned long long m_hConstraintEntity; // 0x10C0
 
}; // size=0x10C8
 
class CEntityFreezing
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	Vector m_vFreezingOrigin; // 0xF68
	DataTable m_flFrozenPerHitbox; // 0xF74
	char __buf_0xF78[0xC4]; // 0xF78
	float m_flFrozen; // 0x103C
	int m_bFinishFreezing; // 0x1040
 
}; // size=0x1044
 
class CEntityFlame
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	unsigned long long m_hEntAttached; // 0xF68
	char __buf_0xF70[0x1C]; // 0xF70
	int m_bCheapEffect; // 0xF8C
 
}; // size=0xF90
 
class CEntityDissolve
{
public:
 
	char __buf_0x00[0xF70]; // 0x0
	float m_flStartTime; // 0xF70
	float m_flFadeOutStart; // 0xF74
	float m_flFadeOutLength; // 0xF78
	float m_flFadeOutModelStart; // 0xF7C
	float m_flFadeOutModelLength; // 0xF80
	float m_flFadeInStart; // 0xF84
	float m_flFadeInLength; // 0xF88
	int m_nDissolveType; // 0xF8C
	char __buf_0xF90[0x4]; // 0xF90
	Vector m_vDissolverOrigin; // 0xF94
	int m_nMagnitude; // 0xFA0
 
}; // size=0xFA4
 
class CEnvQuadraticBeam
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	QAngle m_targetPosition; // 0xF68
	QAngle m_controlPosition; // 0xF74
	float m_scrollRate; // 0xF80
	float m_flWidth; // 0xF84
 
}; // size=0xF88
 
class CEmbers
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_nDensity; // 0xF68
	int m_nLifetime; // 0xF6C
	int m_nSpeed; // 0xF70
	int m_bEmit; // 0xF74
 
}; // size=0xF78
 
class CEnvWind
{
public:
 
	DataTable m_EnvWindShared; // 0xF68
 
}; // size=0xF6C
 
class CPrecipitation
{
public:
 
	int m_nPrecipType; // 0xF94
 
}; // size=0xF98
 
class CDynamicLight
{
public:
 
	char __buf_0x00[0xF65]; // 0x0
	int m_Flags; // 0xF65
	float m_Radius; // 0xF68
	int m_Exponent; // 0xF6C
	float m_InnerAngle; // 0xF70
	float m_OuterAngle; // 0xF74
	float m_SpotRadius; // 0xF78
 
}; // size=0xF7C
 
class CColorCorrectionVolume
{
public:
 
	char __buf_0x00[0xFA4]; // 0x0
	int m_bEnabled; // 0xFA4
	float m_MaxWeight; // 0xFA8
	float m_FadeDuration; // 0xFAC
	float m_Weight; // 0xFB0
	char m_lookupFilename[0x104]; // 0xFB4
 
}; // size=0xFB5
 
class CColorCorrection
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	Vector m_vecOrigin; // 0xF68
	float m_minFalloff; // 0xF74
	float m_maxFalloff; // 0xF78
	float m_flFadeInDuration; // 0xF7C
	float m_flFadeOutDuration; // 0xF80
	float m_flMaxWeight; // 0xF84
	float m_flCurWeight; // 0xF88
	char m_netLookupFilename[0x104]; // 0xF8C
	unsigned char m_bEnabled; // 0x1090
	char __buf_0x1091[0x1]; // 0x1091
	int m_bClientSide; // 0x1092
 
}; // size=0x1096
 
class CBreakableProp
{
public:
 
	char __buf_0x00[0x3010]; // 0x0
	QAngle m_qPreferredPlayerCarryAngles; // 0x3010
	int m_bClientPhysics; // 0x301C
 
}; // size=0x3020
 
class CBeamSpotlight
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_nHaloIndex; // 0xF68
	int m_nRotationAxis; // 0xF6C
	float m_flRotationSpeed; // 0xF70
	int m_bSpotlightOn; // 0xF74
	float m_flSpotlightMaxLength; // 0xF78
	float m_flSpotlightGoalWidth; // 0xF7C
	float m_flHDRColorScale; // 0xF80
 
}; // size=0xF84
 
class CBaseButton
{
public:
 
	int m_usable; // 0xF91
 
}; // size=0xF95
 
class CBaseToggle
{
public:
 
	char __buf_0x00[0xF7C]; // 0x0
	Vector m_vecFinalDest; // 0xF7C
	int m_movementType; // 0xF88
	float m_flMoveTargetTime; // 0xF8C
 
}; // size=0xF90
 
class CBasePlayer
{
public:
 
	char __buf_0x00[0x134]; // 0x0
	int m_iHealth; // 0x134
	int m_fFlags; // 0x138
	char __buf_0x13C[0x48]; // 0x13C
	unsigned long long m_hGroundEntity; // 0x184
	char __buf_0x18C[0x107]; // 0x18C
	int m_lifeState; // 0x293
	char __buf_0x297[0x3211]; // 0x297
	DataTable m_iAmmo; // 0x34A8
	char __buf_0x34AC[0x1CC]; // 0x34AC
	int m_iCoachingTeam; // 0x3678
	char __buf_0x367C[0x64]; // 0x367C
	float m_flDuckAmount; // 0x36E0
	float m_flDuckSpeed; // 0x36E4
	char __buf_0x36E8[0x298]; // 0x36E8
	DataTable pl; // 0x3980
	char __buf_0x3984[0x14]; // 0x3984
	int m_iFOV; // 0x3998
	int m_iFOVStart; // 0x399C
	char __buf_0x39A0[0x14]; // 0x39A0
	int m_ladderSurfaceProps; // 0x39B4
	char __buf_0x39B8[0x4]; // 0x39B8
	float m_flFOVTime; // 0x39BC
	char __buf_0x39C0[0x18]; // 0x39C0
	Vector m_vecLadderNormal; // 0x39D8
	char __buf_0x39E4[0x24]; // 0x39E4
	int m_iBonusProgress; // 0x3A08
	int m_iBonusChallenge; // 0x3A0C
	float m_flMaxspeed; // 0x3A10
	unsigned long long m_hZoomOwner; // 0x3A14
	char __buf_0x3A1C[0x14]; // 0x3A1C
	int m_vphysicsCollisionState; // 0x3A30
	char __buf_0x3A34[0x94]; // 0x3A34
	int m_afPhysicsFlags; // 0x3AC8
	unsigned long long m_hVehicle; // 0x3ACC
	unsigned long long m_hViewModel; // 0x3AD4
	char __buf_0x3ADC[0x34]; // 0x3ADC
	unsigned int m_hUseEntity; // 0x3B10
	int m_iDefaultFOV; // 0x3B14
	char __buf_0x3B18[0x10]; // 0x3B18
	unsigned int m_hViewEntity; // 0x3B28
	int m_bShouldDrawPlayerWhileUsingViewEntity; // 0x3B2C
	char __buf_0x3B30[0x2C]; // 0x3B30
	int m_iDeathPostEffect; // 0x3B5C
	int m_iObserverMode; // 0x3B60
	unsigned char m_bActiveCameraMan; // 0x3B64
	char __buf_0x3B65[0x1]; // 0x3B65
	unsigned char m_bCameraManOverview; // 0x3B66
	char __buf_0x3B67[0x1]; // 0x3B67
	int m_uCameraManGraphs; // 0x3B68
	char __buf_0x3B6C[0x8]; // 0x3B6C
	unsigned long long m_hObserverTarget; // 0x3B74
	char __buf_0x3B7C[0x264]; // 0x3B7C
	char m_szLastPlaceName[0x12]; // 0x3DE0
	char __buf_0x3DF2[0x16]; // 0x3DF2
	int m_ubEFNoInterpParity; // 0x3E08
	char __buf_0x3E0C[0x204]; // 0x3E0C
	unsigned int m_hPostProcessCtrl; // 0x4010
	unsigned long long m_hColorCorrectionCtrl; // 0x4014
	char __buf_0x401C[0x4]; // 0x401C
	int m_PlayerFog_m_hCtrl; // 0x4020
 
}; // size=0x4024
 
class CBaseFlex
{
public:
 
	char __buf_0x00[0x3084]; // 0x0
	Vector m_viewtarget; // 0x3084
	char __buf_0x3090[0x48]; // 0x3090
	DataTable m_flexWeight; // 0x30D8
	char __buf_0x30DC[0x1C4]; // 0x30DC
	int m_blinktoggle; // 0x32A0
 
}; // size=0x32A4
 
class CBaseEntity
{
public:
 
	char __buf_0x00[0x40]; // 0x0
	float m_flLastMadeNoiseTime; // 0x40
	char __buf_0x44[0x4C]; // 0x44
	int m_bIsAutoaimTarget; // 0x90
	char __buf_0x94[0x14]; // 0x94
	int m_clrRender; // 0xA8
	int m_cellbits; // 0xAC
	char __buf_0xB0[0x4]; // 0xB0
	int m_cellX; // 0xB4
	int m_cellY; // 0xB8
	int m_cellZ; // 0xBC
	char __buf_0xC0[0x64]; // 0xC0
	int m_fEffects; // 0x124
	int m_iTeamNum; // 0x128
	int m_iPendingTeamNum; // 0x12C
	char __buf_0x130[0x30]; // 0x130
	QAngle m_angRotation; // 0x160
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
	unsigned long long m_hOwnerEntity; // 0x180
	char m_iName[0x104]; // 0x188
	unsigned char m_nModelIndex; // 0x28C
	char __buf_0x28D[0x1]; // 0x28D
	int m_nRenderFX; // 0x28E
	char __buf_0x292[0xA]; // 0x292
	int m_flSimulationTime; // 0x29C
	char __buf_0x2A0[0x78]; // 0x2A0
	float m_flUseLookAtAngle; // 0x318
	char __buf_0x31C[0x24]; // 0x31C
	int m_iParentAttachment; // 0x340
	char __buf_0x344[0x4]; // 0x344
	float m_fadeMinDist; // 0x348
	float m_fadeMaxDist; // 0x34C
	float m_flFadeScale; // 0x350
	char __buf_0x354[0x24]; // 0x354
	unsigned long long m_Collision; // 0x378
	char __buf_0x380[0xA0]; // 0x380
	float m_flElasticity; // 0x420
	float m_flShadowCastDistance; // 0x424
	char __buf_0x428[0x120]; // 0x428
	int m_CollisionGroup; // 0x548
	char __buf_0x54C[0x97E]; // 0x54C
	unsigned char m_bSimulatedEveryTick; // 0xECA
	char __buf_0xECB[0x1]; // 0xECB
	unsigned char m_bAlternateSorting; // 0xECC
	unsigned char m_bSpotted; // 0xECD
	DataTable m_bSpottedBy; // 0xECE
	char __buf_0xED2[0x3E]; // 0xED2
	DataTable m_bSpottedByMask; // 0xF10
	char __buf_0xF14[0x4]; // 0xF14
	unsigned char m_nMinCPULevel; // 0xF18
	char __buf_0xF19[0x1]; // 0xF19
	unsigned char m_nMinGPULevel; // 0xF1A
	char __buf_0xF1B[0x1]; // 0xF1B
	int m_iTextureFrameIndex; // 0xF1C
	char __buf_0xF20[0x8]; // 0xF20
	unsigned long long m_hEffectEntity; // 0xF28
 
}; // size=0xF30
 
class CBaseDoor
{
public:
 
	float m_flWaveHeight; // 0xF94
 
}; // size=0xF98
 
class CBaseCombatCharacter
{
public:
 
	char __buf_0x00[0x34A4]; // 0x0
	int m_LastHitGroup; // 0x34A4
	char __buf_0x34A8[0x80]; // 0x34A8
	DataTable m_hMyWeapons; // 0x3528
	char __buf_0x352C[0xFC]; // 0x352C
	unsigned int m_hActiveWeapon; // 0x3628
	float m_flTimeOfLastInjury; // 0x362C
	int m_nRelativeDirectionOfLastInjury; // 0x3630
 
}; // size=0x3634
 
class CBoneFollower
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_modelIndex; // 0xF68
	int m_solidIndex; // 0xF6C
 
}; // size=0xF70
 
class CBaseAnimating
{
public:
 
	char __buf_0x00[0x2AD]; // 0x0
	int m_bClientSideRagdoll; // 0x2AD
	char __buf_0x2B1[0xCF7]; // 0x2B1
	int m_nHitboxSet; // 0xFA8
	char __buf_0xFAC[0x28]; // 0xFAC
	float m_flPlaybackRate; // 0xFD4
	int m_nSkin; // 0xFD8
	int m_nBody; // 0xFDC
	char __buf_0xFE0[0x14]; // 0xFE0
	int m_nNewSequenceParity; // 0xFF4
	int m_nResetEventsParity; // 0xFF8
	char __buf_0xFFC[0x8]; // 0xFFC
	DataTable m_flEncodedController; // 0x1004
	char __buf_0x1008[0xC]; // 0x1008
	int m_nMuzzleFlashParity; // 0x1014
	char __buf_0x1018[0x1C20]; // 0x1018
	Vector m_vecForce; // 0x2C38
	int m_nForceBone; // 0x2C44
	char __buf_0x2C48[0x28]; // 0x2C48
	unsigned long long m_pStudioBones; // 0x2C70
	char __buf_0x2C78[0x14]; // 0x2C78
	int m_bClientSideFrameReset; // 0x2C8C
	char __buf_0x2C90[0x40]; // 0x2C90
	float m_flFrozen; // 0x2CD0
	char __buf_0x2CD4[0x5C]; // 0x2CD4
	float m_flModelScale; // 0x2D30
	int m_ScaleType; // 0x2D34
	char __buf_0x2D38[0x30]; // 0x2D38
	DataTable m_flPoseParameter; // 0x2D68
	char __buf_0x2D6C[0x15C]; // 0x2D6C
	int m_bClientSideAnimation; // 0x2EC8
	char __buf_0x2ECC[0x1C]; // 0x2ECC
	int m_nSequence; // 0x2EE8
	char __buf_0x2EEC[0xCC]; // 0x2EEC
	unsigned int m_hLightingOrigin; // 0x2FB8
	char __buf_0x2FBC[0x2]; // 0x2FBC
	int m_bSuppressAnimSounds; // 0x2FBE
 
}; // size=0x2FC2
 
class CAI_BaseNPC
{
public:
 
	char __buf_0x00[0x293]; // 0x0
	int m_lifeState; // 0x293
	char __buf_0x297[0x33A1]; // 0x297
	float m_flTimePingEffect; // 0x3638
	int m_iDeathPose; // 0x363C
	int m_iDeathFrame; // 0x3640
	int m_iSpeedModRadius; // 0x3644
	int m_iSpeedModSpeed; // 0x3648
	unsigned char m_bPerformAvoidance; // 0x364C
	char __buf_0x364D[0x1]; // 0x364D
	unsigned char m_bFadeCorpse; // 0x364E
	char __buf_0x364F[0x1]; // 0x364F
	int m_bImportanRagdoll; // 0x3650
 
}; // size=0x3654
 
class CChicken
{
public:
 
	char __buf_0x00[0x305C]; // 0x0
	int m_jumpedThisFrame; // 0x305C
	int m_leader; // 0x3060
 
}; // size=0x3064
 
class CInferno
{
public:
 
	char __buf_0x00[0xF80]; // 0x0
	DataTable m_fireXDelta; // 0xF80
	char __buf_0xF84[0x18C]; // 0xF84
	DataTable m_fireYDelta; // 0x1110
	char __buf_0x1114[0x18C]; // 0x1114
	DataTable m_fireZDelta; // 0x12A0
	char __buf_0x12A4[0x18C]; // 0x12A4
	DataTable m_bFireIsBurning; // 0x1430
	char __buf_0x1434[0x6A0]; // 0x1434
	int m_fireCount; // 0x1AD4
 
}; // size=0x1AD8
 
class CTEPlantBomb
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	int m_iPlayer; // 0x20
	Vector m_vecOrigin; // 0x24
	int m_option; // 0x30
 
}; // size=0x34
 
class CTEFireBullets
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	int m_iPlayer; // 0x20
	int m_nItemDefIndex; // 0x24
	Vector m_vecOrigin; // 0x28
	Vector m_vecAngles; // 0x34
	int m_iWeaponID; // 0x40
	int m_iMode; // 0x44
	int m_iSeed; // 0x48
	float m_fInaccuracy; // 0x4C
	float m_fSpread; // 0x50
	int m_iSoundType; // 0x54
 
}; // size=0x58
 
class CTERadioIcon
{
public:
 
	int m_iAttachToClient; // 0x20
 
}; // size=0x24
 
class CPlantedC4
{
public:
 
	char __buf_0x00[0x3001]; // 0x0
	int m_bBombTicking; // 0x3001
	char __buf_0x3005[0x7]; // 0x3005
	float m_flC4Blow; // 0x300C
	float m_flTimerLength; // 0x3010
	char __buf_0x3014[0xC]; // 0x3014
	float m_flDefuseLength; // 0x3020
	float m_flDefuseCountDown; // 0x3024
	int m_bBombDefused; // 0x3028
	unsigned long long m_hBombDefuser; // 0x302C
 
}; // size=0x3034
 
class CCSPlayerResource
{
public:
 
	char __buf_0x00[0x1CB4]; // 0x0
	int m_iPlayerC4; // 0x1CB4
	int m_iPlayerVIP; // 0x1CB8
	QAngle m_bombsiteCenterA; // 0x1CBC
	QAngle m_bombsiteCenterB; // 0x1CC8
	DataTable m_bHostageAlive; // 0x1CD4
	char __buf_0x1CD8[0x8]; // 0x1CD8
	DataTable m_isHostageFollowingSomeone; // 0x1CE0
	char __buf_0x1CE4[0x8]; // 0x1CE4
	DataTable m_iHostageEntityIDs; // 0x1CEC
	char __buf_0x1CF0[0x2C]; // 0x1CF0
	DataTable m_hostageRescueX; // 0x1D1C
	char __buf_0x1D20[0xC]; // 0x1D20
	DataTable m_hostageRescueY; // 0x1D2C
	char __buf_0x1D30[0xC]; // 0x1D30
	DataTable m_hostageRescueZ; // 0x1D3C
	char __buf_0x1D40[0xC]; // 0x1D40
	DataTable m_iMVPs; // 0x1D4C
	char __buf_0x1D50[0x100]; // 0x1D50
	DataTable m_bHasDefuser; // 0x1E50
	char __buf_0x1E54[0x3D]; // 0x1E54
	DataTable m_bHasHelmet; // 0x1E91
	char __buf_0x1E95[0x3F]; // 0x1E95
	DataTable m_iArmor; // 0x1ED4
	char __buf_0x1ED8[0x100]; // 0x1ED8
	DataTable m_iScore; // 0x1FD8
	char __buf_0x1FDC[0x100]; // 0x1FDC
	DataTable m_iCompetitiveRanking; // 0x20DC
	char __buf_0x20E0[0x100]; // 0x20E0
	DataTable m_iCompetitiveWins; // 0x21E0
	char __buf_0x21E4[0x100]; // 0x21E4
	DataTable m_iCompTeammateColor; // 0x22E4
	char __buf_0x22E8[0x100]; // 0x22E8
	DataTable m_bControllingBot; // 0x23E8
	char __buf_0x23EC[0x40]; // 0x23EC
	DataTable m_iControlledPlayer; // 0x242C
	char __buf_0x2430[0x100]; // 0x2430
	DataTable m_iControlledByPlayer; // 0x2530
	char __buf_0x2534[0x2180]; // 0x2534
	DataTable m_iBotDifficulty; // 0x46B4
	char __buf_0x46B8[0x100]; // 0x46B8
	DataTable m_szClan; // 0x47B8
	char __buf_0x47BC[0x40C]; // 0x47BC
	DataTable m_iTotalCashSpent; // 0x4BC8
	char __buf_0x4BCC[0x100]; // 0x4BCC
	DataTable m_iCashSpentThisRound; // 0x4CCC
	char __buf_0x4CD0[0x100]; // 0x4CD0
	DataTable m_nEndMatchNextMapVotes; // 0x4DD0
	char __buf_0x4DD4[0x100]; // 0x4DD4
	int m_bEndMatchNextMapAllVoted; // 0x4ED4
	DataTable m_nActiveCoinRank; // 0x4ED8
	char __buf_0x4EDC[0x100]; // 0x4EDC
	DataTable m_nMusicID; // 0x4FDC
	char __buf_0x4FE0[0x144]; // 0x4FE0
	DataTable m_nPersonaDataPublicLevel; // 0x5124
	char __buf_0x5128[0x100]; // 0x5128
	DataTable m_nPersonaDataPublicCommendsLeader; // 0x5228
	char __buf_0x522C[0x100]; // 0x522C
	DataTable m_nPersonaDataPublicCommendsTeacher; // 0x532C
	char __buf_0x5330[0x100]; // 0x5330
	DataTable m_nPersonaDataPublicCommendsFriendly; // 0x5430
 
}; // size=0x5434
 
class CCSPlayer
{
public:
 
	char __buf_0x00[0x4164]; // 0x0
	unsigned char m_bIsScoped; // 0x4164
	char __buf_0x4165[0x1]; // 0x4165
	unsigned char m_bResumeZoom; // 0x4166
	char __buf_0x4167[0x1]; // 0x4167
	int m_iPlayerState; // 0x4168
	unsigned char m_bIsDefusing; // 0x416C
	char __buf_0x416D[0x1]; // 0x416D
	unsigned char m_bIsRescuing; // 0x416E
	char __buf_0x416F[0x1]; // 0x416F
	float m_fImmuneToGunGameDamageTime; // 0x4170
	char __buf_0x4174[0x4]; // 0x4174
	unsigned char m_bGunGameImmunity; // 0x4178
	char __buf_0x4179[0x1]; // 0x4179
	unsigned char m_bMadeFinalGunGameProgressiveKill; // 0x417A
	char __buf_0x417B[0x1]; // 0x417B
	int m_iGunGameProgressiveWeaponIndex; // 0x417C
	int m_iNumGunGameTRKillPoints; // 0x4180
	int m_iNumGunGameKillsWithCurrentWeapon; // 0x4184
	int m_iNumRoundKills; // 0x4188
	int m_iNumRoundKillsHeadshots; // 0x418C
	float m_fMolotovUseTime; // 0x4190
	float m_fMolotovDamageTime; // 0x4194
	unsigned char m_bInBombZone; // 0x4198
	char __buf_0x4199[0x1]; // 0x4199
	unsigned char m_bInNoDefuseArea; // 0x419A
	char __buf_0x419B[0x1]; // 0x419B
	int m_iThrowGrenadeCounter; // 0x419C
	int m_bWaitForNoAttack; // 0x41A0
	float m_flGuardianTooFarDistFrac; // 0x41A4
	float m_flDetectedByEnemySensorTime; // 0x41A8
	char __buf_0x41AC[0x4]; // 0x41AC
	int m_bKilledByTaser; // 0x41B0
	int m_iMoveState; // 0x41B4
	unsigned char m_bCanMoveDuringFreezePeriod; // 0x41B8
	char __buf_0x41B9[0x1]; // 0x41B9
	int m_isCurrentGunGameTeamLeader; // 0x41BA
	char __buf_0x41BE[0xFE]; // 0x41BE
	float m_flLowerBodyYawTarget; // 0x42BC
	int m_bStrafing; // 0x42C0
	char __buf_0x42C4[0x68D0]; // 0x42C4
	int m_iAddonBits; // 0xAB94
	int m_iPrimaryAddon; // 0xAB98
	int m_iSecondaryAddon; // 0xAB9C
	int m_iProgressBarDuration; // 0xABA0
	float m_flProgressBarStartTime; // 0xABA4
	char __buf_0xABA8[0x11]; // 0xABA8
	int m_bNightVisionOn; // 0xABB9
	char __buf_0xABBD[0x3]; // 0xABBD
	float m_flGroundAccelLinearFracLastTime; // 0xABC0
	int m_iStartAccount; // 0xABC4
	int m_totalHitsOnServer; // 0xABC8
	char __buf_0xABCC[0x4]; // 0xABCC
	unsigned int m_hRagdoll; // 0xABD0
	unsigned int m_hCarriedHostage; // 0xABD4
	unsigned long long m_hCarriedHostageProp; // 0xABD8
	char __buf_0xABE0[0x14]; // 0xABE0
	float m_flFlashMaxAlpha; // 0xABF4
	float m_flFlashDuration; // 0xABF8
	char __buf_0xABFC[0x48]; // 0xABFC
	DataTable m_iMatchStats_Kills; // 0xAC44
	char __buf_0xAC48[0x74]; // 0xAC48
	DataTable m_iMatchStats_Damage; // 0xACBC
	char __buf_0xACC0[0x74]; // 0xACC0
	DataTable m_iMatchStats_EquipmentValue; // 0xAD34
	char __buf_0xAD38[0x74]; // 0xAD38
	DataTable m_iMatchStats_MoneySaved; // 0xADAC
	char __buf_0xADB0[0x74]; // 0xADB0
	DataTable m_iMatchStats_KillReward; // 0xAE24
	char __buf_0xAE28[0x74]; // 0xAE28
	DataTable m_iMatchStats_LiveTime; // 0xAE9C
	char __buf_0xAEA0[0x74]; // 0xAEA0
	DataTable m_iMatchStats_Deaths; // 0xAF14
	char __buf_0xAF18[0x74]; // 0xAF18
	DataTable m_iMatchStats_Assists; // 0xAF8C
	char __buf_0xAF90[0x74]; // 0xAF90
	DataTable m_iMatchStats_HeadShotKills; // 0xB004
	char __buf_0xB008[0x74]; // 0xB008
	DataTable m_iMatchStats_Objective; // 0xB07C
	char __buf_0xB080[0x74]; // 0xB080
	DataTable m_iMatchStats_CashEarned; // 0xB0F4
	char __buf_0xB0F8[0x74]; // 0xB0F8
	DataTable m_iMatchStats_UtilityDamage; // 0xB16C
	char __buf_0xB170[0x74]; // 0xB170
	DataTable m_iMatchStats_EnemiesFlashed; // 0xB1E4
	char __buf_0xB1E8[0xF0]; // 0xB1E8
	unsigned char m_unCurrentEquipmentValue; // 0xB2D8
	char __buf_0xB2D9[0x1]; // 0xB2D9
	unsigned char m_unRoundStartEquipmentValue; // 0xB2DA
	char __buf_0xB2DB[0x1]; // 0xB2DB
	int m_unFreezetimeEndEquipmentValue; // 0xB2DC
	DataTable m_rank; // 0xB2E0
	char __buf_0xB2E4[0x14]; // 0xB2E4
	int m_unMusicID; // 0xB2F8
	int m_iAccount; // 0xB2FC
	int m_bHasHelmet; // 0xB300
	int m_iClass; // 0xB304
	int m_ArmorValue; // 0xB308
	QAngle m_angEyeAngles; // 0xB30C
	int m_bHasDefuser; // 0xB318
	char __buf_0xB31C[0x1E]; // 0xB31C
	unsigned char m_bHud_MiniScoreHidden; // 0xB33A
	char __buf_0xB33B[0x1]; // 0xB33B
	int m_nLastKillerIndex; // 0xB33C
	int m_nLastConcurrentKilled; // 0xB340
	int m_nDeathCamMusic; // 0xB344
	char __buf_0xB348[0x160]; // 0xB348
	int m_cycleLatch; // 0xB4A8
	char __buf_0xB4AC[0x190]; // 0xB4AC
	int m_bIsLookingAtWeapon; // 0xB63C
	char __buf_0xB640[0x95]; // 0xB640
	unsigned char m_bIsAssassinationTarget; // 0xB6D5
	char __buf_0xB6D6[0x1]; // 0xB6D6
	int m_bCanControlObservedBot; // 0xB6D7
	char __buf_0xB6DB[0x9]; // 0xB6DB
	int m_bHasControlledBotThisRound; // 0xB6E4
 
}; // size=0xB6E8
 
class CCSRagdoll
{
public:
 
	char __buf_0x00[0x128]; // 0x0
	int m_iTeamNum; // 0x128
	char __buf_0x12C[0x40]; // 0x12C
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x114]; // 0x178
	int m_nModelIndex; // 0x28C
	char __buf_0x290[0x29A8]; // 0x290
	Vector m_vecForce; // 0x2C38
	int m_nForceBone; // 0x2C44
	char __buf_0x2C48[0x28]; // 0x2C48
	unsigned long long m_pStudioBones; // 0x2C70
	char __buf_0x2C78[0x250]; // 0x2C78
	int m_bClientSideAnimation; // 0x2EC8
	char __buf_0x2ECC[0x1B8]; // 0x2ECC
	unsigned long long m_hPlayer; // 0x3084
	char __buf_0x308C[0x8]; // 0x308C
	Vector m_vecRagdollVelocity; // 0x3094
	Vector m_vecRagdollOrigin; // 0x30A0
	int m_iDeathPose; // 0x30AC
	int m_iDeathFrame; // 0x30B0
	float m_flDeathYaw; // 0x30B4
	float m_flAbsYaw; // 0x30B8
 
}; // size=0x30BC
 
class CTEPlayerAnimEvent
{
public:
 
	char __buf_0x00[0x20]; // 0x0
	unsigned int m_hPlayer; // 0x20
	int m_iEvent; // 0x24
	int m_nData; // 0x28
 
}; // size=0x2C
 
class CHostage
{
public:
 
	char __buf_0x00[0x134]; // 0x0
	int m_iHealth; // 0x134
	int m_fFlags; // 0x138
	char __buf_0x13C[0x157]; // 0x13C
	int m_lifeState; // 0x293
	char __buf_0x297[0x33AD]; // 0x297
	int m_iMaxHealth; // 0x3644
	char __buf_0x3648[0x8]; // 0x3648
	int m_leader; // 0x3650
	Vector m_vel; // 0x3654
	int m_isRescued; // 0x3660
	int m_nHostageState; // 0x3664
	float m_flRescueStartTime; // 0x3668
	float m_flGrabSuccessTime; // 0x366C
	float m_flDropStartTime; // 0x3670
 
}; // size=0x3674
 
class CHandleTest
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	int m_Handle; // 0xF68
	int m_bSendHandle; // 0xF6C
 
}; // size=0xF70
 
class CSpriteTrail
{
public:
 
	char __buf_0x00[0x1604]; // 0x0
	float m_flLifeTime; // 0x1604
	float m_flStartWidth; // 0x1608
	float m_flEndWidth; // 0x160C
	float m_flStartWidthVariance; // 0x1610
	float m_flTextureRes; // 0x1614
	float m_flMinFadeLength; // 0x1618
	Vector m_vecSkyboxOrigin; // 0x161C
	float m_flSkyboxScale; // 0x1628
 
}; // size=0x162C
 
class CSprite
{
public:
 
	char __buf_0x00[0xF7C]; // 0x0
	unsigned int m_hAttachedToEntity; // 0xF7C
	int m_nAttachment; // 0xF80
	float m_flSpriteFramerate; // 0xF84
	float m_flFrame; // 0xF88
	char __buf_0xF8C[0x4]; // 0xF8C
	int m_nBrightness; // 0xF90
	float m_flBrightnessTime; // 0xF94
	float m_flSpriteScale; // 0xF98
	float m_flScaleTime; // 0xF9C
	int m_bWorldSpaceScale; // 0xFA0
	float m_flGlowProxySize; // 0xFA4
	float m_flHDRColorScale; // 0xFA8
 
}; // size=0xFAC
 
class CPoseController
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	DataTable m_hProps; // 0xF68
	char __buf_0xF6C[0xC]; // 0xF6C
	DataTable m_chPoseIndex; // 0xF78
	int m_bPoseValueParity; // 0xF7C
	float m_fPoseValue; // 0xF80
	float m_fInterpolationTime; // 0xF84
	int m_bInterpolationWrap; // 0xF88
	float m_fCycleFrequency; // 0xF8C
	int m_nFModType; // 0xF90
	float m_fFModTimeOffset; // 0xF94
	float m_fFModRate; // 0xF98
	float m_fFModAmplitude; // 0xF9C
 
}; // size=0xFA0
 
class CFuncLadder
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	Vector m_vecLadderDir; // 0xF68
	char __buf_0xF74[0x24]; // 0xF74
	Vector m_vecPlayerMountPositionTop; // 0xF98
	Vector m_vecPlayerMountPositionBottom; // 0xFA4
	char __buf_0xFB0[0x1]; // 0xFB0
	int m_bFakeLadder; // 0xFB1
 
}; // size=0xFB5
 
class CEnvDetailController
{
public:
 
	char __buf_0x00[0xF68]; // 0x0
	float m_flFadeStartDist; // 0xF68
	float m_flFadeEndDist; // 0xF6C
 
}; // size=0xF70
 
class CBaseAttributableItem
{
public:
 
	char __buf_0x00[0x34C0]; // 0x0
	DataTable m_AttributeManager; // 0x34C0
	char __buf_0x34C4[0x4EC]; // 0x34C4
	int m_OriginalOwnerXuidLow; // 0x39B0
	int m_OriginalOwnerXuidHigh; // 0x39B4
	int m_nFallbackPaintKit; // 0x39B8
	int m_nFallbackSeed; // 0x39BC
	float m_flFallbackWear; // 0x39C0
	int m_nFallbackStatTrak; // 0x39C4
 
}; // size=0x39C8
 
class CEconEntity
{
public:
 
	char __buf_0x00[0x34C0]; // 0x0
	DataTable m_AttributeManager; // 0x34C0
	char __buf_0x34C4[0x4EC]; // 0x34C4
	int m_OriginalOwnerXuidLow; // 0x39B0
	int m_OriginalOwnerXuidHigh; // 0x39B4
	int m_nFallbackPaintKit; // 0x39B8
	int m_nFallbackSeed; // 0x39BC
	float m_flFallbackWear; // 0x39C0
	int m_nFallbackStatTrak; // 0x39C4
 
}; // size=0x39C8
 
class CWeaponXM1014
{
public:
 
	int m_reloadState; // 0x3BB8
 
}; // size=0x3BBC
 
class CWeaponSawedoff
{
public:
 
	int m_reloadState; // 0x3BB8
 
}; // size=0x3BBC
 
class CWeaponNOVA
{
public:
 
	int m_reloadState; // 0x3BB8
 
}; // size=0x3BBC
 
class CWeaponM3
{
public:
 
	int m_reloadState; // 0x3BB8
 
}; // size=0x3BBC
 
class CWeaponCSBaseGun
{
public:
 
	char __buf_0x00[0x3BB4]; // 0x0
	int m_zoomLevel; // 0x3BB4
	int m_iBurstShotsRemaining; // 0x3BB8
 
}; // size=0x3BBC
 
class CWeaponCSBase
{
public:
 
	char __buf_0x00[0x3B18]; // 0x0
	int m_weaponMode; // 0x3B18
	float m_fAccuracyPenalty; // 0x3B1C
	char __buf_0x3B20[0x8]; // 0x3B20
	int m_iRecoilIndex; // 0x3B28
	float m_flRecoilIndex; // 0x3B2C
	int m_bBurstMode; // 0x3B30
	float m_flPostponeFireReadyTime; // 0x3B34
	int m_bReloadVisuallyComplete; // 0x3B38
	float m_flDoneSwitchingSilencer; // 0x3B3C
	char __buf_0x3B40[0x4]; // 0x3B40
	int m_iOriginalTeamNumber; // 0x3B44
	char __buf_0x3B48[0x14]; // 0x3B48
	unsigned long long m_hPrevOwner; // 0x3B5C
	char __buf_0x3B64[0x2C]; // 0x3B64
	float m_fLastShotTime; // 0x3B90
	char __buf_0x3B94[0x1C]; // 0x3B94
	int m_iIronSightMode; // 0x3BB0
 
}; // size=0x3BB4
 
class CC4
{
public:
 
	char __buf_0x00[0x3BF4]; // 0x0
	int m_bStartedArming; // 0x3BF4
	float m_fArmedTime; // 0x3BF8
	unsigned char m_bBombPlacedAnimation; // 0x3BFC
	char __buf_0x3BFD[0x1]; // 0x3BFD
	int m_bIsPlantingViaUse; // 0x3BFE
 
}; // size=0x3C02
 
class CWeaponBaseItem
{
public:
 
	int m_bRedraw; // 0x3BC8
 
}; // size=0x3BCC
 
class CBaseCSGrenade
{
public:
 
	char __buf_0x00[0x3BB4]; // 0x0
	unsigned char m_bRedraw; // 0x3BB4
	char __buf_0x3BB5[0x1]; // 0x3BB5
	unsigned char m_bPinPulled; // 0x3BB6
	char __buf_0x3BB7[0x1]; // 0x3BB7
	float m_fThrowTime; // 0x3BB8
	int m_bLoopingSoundPlaying; // 0x3BBC
	float m_flThrowStrength; // 0x3BC0
 
}; // size=0x3BC4
 
class CSmokeGrenadeProjectile
{
public:
 
	char __buf_0x00[0x3054]; // 0x0
	int m_nSmokeEffectTickBegin; // 0x3054
	int m_bDidSmokeEffect; // 0x3058
 
}; // size=0x305C
 
class CMolotovProjectile
{
public:
 
	int m_bIsIncGrenade; // 0x3054
 
}; // size=0x3058
 
class CFootstepControl
{
public:
 
	char __buf_0x00[0xF92]; // 0x0
	char m_source[0x10]; // 0xF92
	char m_destination[0x10]; // 0xFA2
 
}; // size=0xFA3
 
class CBaseCSGrenadeProjectile
{
public:
 
	char __buf_0x00[0x3030]; // 0x0
	Vector m_vInitialVelocity; // 0x3030
	int m_nBounces; // 0x303C
 
}; // size=0x3040
 
class CBeam
{
public:
 
	char __buf_0x00[0xA8]; // 0x0
	int m_clrRender; // 0xA8
	char __buf_0xAC[0xC0]; // 0xAC
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0x4]; // 0x178
	int moveparent; // 0x17C
	char __buf_0x180[0x10C]; // 0x180
	unsigned char m_nModelIndex; // 0x28C
	char __buf_0x28D[0x1]; // 0x28D
	int m_nRenderFX; // 0x28E
	char __buf_0x292[0xCD6]; // 0x292
	float m_flFrameRate; // 0xF68
	float m_flHDRColorScale; // 0xF6C
	char __buf_0xF70[0x8]; // 0xF70
	int m_nNumBeamEnts; // 0xF78
	char __buf_0xF7C[0x4]; // 0xF7C
	int m_nHaloIndex; // 0xF80
	int m_nBeamType; // 0xF84
	int m_nBeamFlags; // 0xF88
	DataTable m_hAttachEntity; // 0xF8C
	char __buf_0xF90[0x24]; // 0xF90
	DataTable m_nAttachIndex; // 0xFB4
	char __buf_0xFB8[0x24]; // 0xFB8
	float m_fWidth; // 0xFDC
	float m_fEndWidth; // 0xFE0
	float m_fFadeLength; // 0xFE4
	float m_fHaloScale; // 0xFE8
	float m_fAmplitude; // 0xFEC
	float m_fStartFrame; // 0xFF0
	float m_fSpeed; // 0xFF4
	float m_flFrame; // 0xFF8
	int m_nClipStyle; // 0xFFC
	Vector m_vecEndPos; // 0x1000
 
}; // size=0x100C
 
class CBaseViewModel
{
public:
 
	char __buf_0x00[0x124]; // 0x0
	int m_fEffects; // 0x124
	char __buf_0x128[0x164]; // 0x128
	int m_nModelIndex; // 0x28C
	char __buf_0x290[0xD44]; // 0x290
	float m_flPlaybackRate; // 0xFD4
	int m_nSkin; // 0xFD8
	int m_nBody; // 0xFDC
	char __buf_0xFE0[0x14]; // 0xFE0
	int m_nNewSequenceParity; // 0xFF4
	int m_nResetEventsParity; // 0xFF8
	char __buf_0xFFC[0x18]; // 0xFFC
	int m_nMuzzleFlashParity; // 0x1014
	char __buf_0x1018[0x1ED0]; // 0x1018
	int m_nSequence; // 0x2EE8
	char __buf_0x2EEC[0x130]; // 0x2EEC
	int m_bShouldIgnoreOffsetAndAccuracy; // 0x301C
	char __buf_0x3020[0x38]; // 0x3020
	int m_nViewModelIndex; // 0x3058
	int m_nAnimationParity; // 0x305C
	unsigned int m_hWeapon; // 0x3060
	unsigned long long m_hOwner; // 0x3064
 
}; // size=0x306C
 
class CBaseGrenade
{
public:
 
	char __buf_0x00[0x138]; // 0x0
	int m_fFlags; // 0x138
	char __buf_0x13C[0xC]; // 0x13C
	Vector m_vecVelocity; // 0x148
	char __buf_0x154[0x2EAE]; // 0x154
	unsigned char m_bIsLive; // 0x3002
	char __buf_0x3003[0x1]; // 0x3003
	float m_DmgRadius; // 0x3004
	char __buf_0x3008[0x10]; // 0x3008
	float m_flDamage; // 0x3018
	char __buf_0x301C[0xC]; // 0x301C
	unsigned long long m_hThrower; // 0x3028
 
}; // size=0x3030
 
class CBaseCombatWeapon
{
public:
 
	char __buf_0x00[0x3A30]; // 0x0
	unsigned long long m_hOwner; // 0x3A30
	char __buf_0x3A38[0x8]; // 0x3A38
	int m_iViewModelIndex; // 0x3A40
	int m_iWorldModelIndex; // 0x3A44
	int m_iWorldDroppedModelIndex; // 0x3A48
	char __buf_0x3A4C[0x4]; // 0x3A4C
	int m_iNumEmptyAttacks; // 0x3A50
	unsigned int m_hWeaponWorldModel; // 0x3A54
	int m_iState; // 0x3A58
	char __buf_0x3A5C[0x8]; // 0x3A5C
	int m_iClip1; // 0x3A64
	int m_iClip2; // 0x3A68
	int m_iPrimaryReserveAmmoCount; // 0x3A6C
	int m_iSecondaryReserveAmmoCount; // 0x3A70
 
}; // size=0x3A74
 
class CBaseWeaponWorldModel
{
public:
 
	char __buf_0x00[0x124]; // 0x0
	int m_fEffects; // 0x124
	char __buf_0x128[0x54]; // 0x128
	int moveparent; // 0x17C
	char __buf_0x180[0x10C]; // 0x180
	int m_nModelIndex; // 0x28C
	char __buf_0x290[0xD4C]; // 0x290
	int m_nBody; // 0xFDC
	char __buf_0xFE0[0x20A4]; // 0xFE0
	unsigned long long m_hCombatWeaponParent; // 0x3084
 
}; // size=0x308C
 
class C_BaseEntity
{
public:
 
	char __buf_0x00[0xCC]; // 0x0
	Vector m_vecAbsVelocity; // 0xCC
	Vector m_vecAbsOrigin; // 0xD8
	Vector m_vecOrigin; // 0xE4
	Vector m_vecAngVelocity; // 0xF0
	QAngle m_angAbsRotation; // 0xFC
	QAngle m_angRotation; // 0x108
	float m_flGravity; // 0x114
	float m_flProxyRandomValue; // 0x118
	int m_iEFlags; // 0x11C
	unsigned char m_nWaterType; // 0x120
	unsigned char m_bDormant; // 0x121
	char __buf_0x122[0x2]; // 0x122
	float m_fEffects; // 0x124
	int m_iTeamNum; // 0x128
	int m_iPendingTeamNum; // 0x12C
	char __buf_0x130[0x4]; // 0x130
	int m_iHealth; // 0x134
	int m_fFlags; // 0x138
	Vector m_vecViewOffset; // 0x13C
	Vector m_vecVelocity; // 0x148
	Vector m_vecBaseVelocity; // 0x154
	QAngle m_angNetworkAngles; // 0x160
	Vector m_vecNetworkOrigin; // 0x16C
	float m_flFriction; // 0x178
	unsigned long long m_hNetworkMoveParent; // 0x17C
	unsigned long long m_hOwnerEntity; // 0x180
	unsigned long long m_hGroundEntity; // 0x184
	char __buf_0x18C[0x100]; // 0x18C
	unsigned char m_nModelIndex; // 0x28C
	char __buf_0x28D[0x1]; // 0x28D
	unsigned char m_nRenderFX; // 0x28E
	unsigned char m_nRenderMode; // 0x28F
	char m_MoveType; // 0x290
	char m_MoveCollide; // 0x291
	unsigned char m_nWaterLevel; // 0x292
	char __buf_0x293[0x85]; // 0x293
	float m_flUseLookAtAngle; // 0x318
	char __buf_0x31C[0x54]; // 0x31C
	char m_ModelName; // 0x370
	char __buf_0x371[0x7]; // 0x371
	unsigned long long m_Collision; // 0x378
	char __buf_0x380[0x198]; // 0x380
	char m_rgflCoordinateFrame; // 0x518
	char __buf_0x519[0x9AF]; // 0x519
	unsigned char m_bEverHadPredictionErrorsForThisCommand; // 0xEC8
 
}; // size=0xEC9
 
class C_BasePlayer
{
public:
 
	char __buf_0x00[0x130]; // 0x0
	unsigned char m_nNextThinkTick; // 0x130
	char __buf_0x131[0x3]; // 0x131
	int m_iHealth; // 0x134
	char __buf_0x138[0x1C]; // 0x138
	Vector m_vecBaseVelocity; // 0x154
	char __buf_0x160[0x24]; // 0x160
	unsigned long long m_hGroundEntity; // 0x184
	char __buf_0x18C[0x106]; // 0x18C
	unsigned char m_nWaterLevel; // 0x292
	char m_lifeState; // 0x293
	char __buf_0x294[0x344C]; // 0x294
	float m_flDuckAmount; // 0x36E0
	float m_flDuckSpeed; // 0x36E4
	char __buf_0x36E8[0x8]; // 0x36E8
	char m_Local; // 0x36F0
	char __buf_0x36F1[0x2A7]; // 0x36F1
	int m_iFOV; // 0x3998
	int m_iFOVStart; // 0x399C
	char m_afButtonLast; // 0x39A0
	char __buf_0x39A1[0x3]; // 0x39A1
	char m_afButtonPressed; // 0x39A4
	char __buf_0x39A5[0x3]; // 0x39A5
	char m_afButtonReleased; // 0x39A8
	char __buf_0x39A9[0x3]; // 0x39A9
	unsigned char m_nButtons; // 0x39AC
	char __buf_0x39AD[0x3]; // 0x39AD
	unsigned char m_nImpulse; // 0x39B0
	char __buf_0x39B1[0x3]; // 0x39B1
	char m_ladderSurfaceProps; // 0x39B4
	char __buf_0x39B5[0x3]; // 0x39B5
	float m_flPhysics; // 0x39B8
	float m_flFOVTime; // 0x39BC
	float m_flWaterJumpTime; // 0x39C0
	float m_flSwimSoundTime; // 0x39C4
	int m_ignoreLadderJumpTime; // 0x39C8
	unsigned char m_bHasWalkMovedSinceLastJump; // 0x39CC
	char __buf_0x39CD[0x3]; // 0x39CD
	float m_flStepSoundTime; // 0x39D0
	char m_surfaceFriction; // 0x39D4
	char __buf_0x39D5[0x3]; // 0x39D5
	Vector m_vecLadderNormal; // 0x39D8
	char m_szAnimExtension; // 0x39E4
	char __buf_0x39E5[0x23]; // 0x39E5
	int m_iBonusProgress; // 0x3A08
	int m_iBonusChallenge; // 0x3A0C
	float m_flMaxspeed; // 0x3A10
	unsigned long long m_hZoomOwner; // 0x3A14
	char __buf_0x3A1C[0x14]; // 0x3A1C
	char m_vphysicsCollisionState; // 0x3A30
	char __buf_0x3A31[0x3]; // 0x3A31
	char m_oldOrigin; // 0x3A34
	char __buf_0x3A35[0xB]; // 0x3A35
	unsigned char m_bTouchedPhysObject; // 0x3A40
	unsigned char m_bPhysicsWasFrozen; // 0x3A41
	char __buf_0x3A42[0x2]; // 0x3A42
	char m_vNewVPhysicsPosition; // 0x3A44
	char __buf_0x3A45[0xB]; // 0x3A45
	char m_vNewVPhysicsVelocity; // 0x3A50
	char __buf_0x3A51[0x77]; // 0x3A51
	char m_afPhysicsFlags; // 0x3AC8
	char __buf_0x3AC9[0x3]; // 0x3AC9
	unsigned long long m_hVehicle; // 0x3ACC
	unsigned long long m_hLastWeapon; // 0x3AD0
	unsigned long long m_hViewModel; // 0x3AD4
	char __buf_0x3ADC[0x30]; // 0x3ADC
	float m_fOnTarget; // 0x3B0C
	char __buf_0x3B10[0x130]; // 0x3B10
	unsigned char m_nTickBase; // 0x3C40
	char __buf_0x3C41[0x193]; // 0x3C41
	Vector m_vecPreviouslyPredictedOrigin; // 0x3DD4
 
}; // size=0x3DE0
 
class CPlayerState
{
public:
 
	char __buf_0x00[0x36F0]; // 0x0
	char __buf_0x36F0[0x40]; // 0x36F0
	unsigned char m_nStepside; // 0x3730
	char __buf_0x3731[0x3]; // 0x3731
	unsigned char m_nOldButtons; // 0x3734
	char __buf_0x3735[0x3]; // 0x3735
	float m_flFOVRate; // 0x3738
	int m_iHideHUD; // 0x373C
	unsigned char m_nDuckTimeMsecs; // 0x3740
	char __buf_0x3741[0x3]; // 0x3741
	unsigned char m_nDuckJumpTimeMsecs; // 0x3744
	char __buf_0x3745[0x3]; // 0x3745
	unsigned char m_nJumpTimeMsecs; // 0x3748
	char __buf_0x3749[0x3]; // 0x3749
	float m_flFallVelocity; // 0x374C
	char __buf_0x3750[0x4]; // 0x3750
	float m_flStepSize; // 0x3754
	Vector m_viewPunchAngle; // 0x3758
	Vector m_aimPunchAngle; // 0x3764
	Vector m_aimPunchAngleVel; // 0x3770
	unsigned char m_bDucked; // 0x377C
	unsigned char m_bDucking; // 0x377D
	char __buf_0x377E[0x2]; // 0x377E
	float m_flLastDuckTime; // 0x3780
	unsigned char m_bInDuckJump; // 0x3784
	unsigned char m_bDrawViewmodel; // 0x3785
	unsigned char m_bWearingSuit; // 0x3786
	unsigned char m_bPoisoned; // 0x3787
	unsigned char m_bAllowAutoMovement; // 0x3788
 
}; // size=0x3789
 
class DT_CSLocalPlayerExclusive
{
public:
 
	char __buf_0x00[0x16C]; // 0x0
	Vector m_vecOrigin; // 0x16C
	char __buf_0x178[0xAA30]; // 0x178
	float m_flStamina; // 0xABA8
	int m_iDirection; // 0xABAC
	int m_iShotsFired; // 0xABB0
	unsigned char m_nNumFastDucks; // 0xABB4
	char __buf_0xABB5[0x3]; // 0xABB5
	unsigned char m_bDuckOverride; // 0xABB8
	char __buf_0xABB9[0x3]; // 0xABB9
	float m_flVelocityModifier; // 0xABBC
	char __buf_0xABC0[0x714]; // 0xABC0
	unsigned char m_nQuestProgressReason; // 0xB2D4
	char __buf_0xB2D5[0x1DB]; // 0xB2D5
	unsigned char m_bPlayerDominated; // 0xB4B0
	char __buf_0xB4B1[0x40]; // 0xB4B1
	unsigned char m_bPlayerDominatingMe; // 0xB4F1
	char __buf_0xB4F2[0x42]; // 0xB4F2
	int m_iWeaponPurchasesThisRound; // 0xB534
 
}; // size=0xB538
 
class DT_LocalWeaponData
{
public:
 
	char __buf_0x00[0x3A34]; // 0x0
	unsigned char m_nViewModelIndex; // 0x3A34
	char __buf_0x3A35[0x17]; // 0x3A35
	int m_iWeaponModule; // 0x3A4C
	char __buf_0x3A50[0xC]; // 0x3A50
	int m_iPrimaryAmmoType; // 0x3A5C
	int m_iSecondaryAmmoType; // 0x3A60
	char __buf_0x3A64[0x64]; // 0x3A64
	unsigned char m_bFlipViewModel; // 0x3AC8
	char __buf_0x3AC9[0x3]; // 0x3AC9
	int m_iWeaponOrigin; // 0x3ACC
 
}; // size=0x3AD0
 
class DT_LocalActiveWeaponData
{
public:
 
	char __buf_0x00[0x130]; // 0x0
	unsigned char m_nNextThinkTick; // 0x130
	char __buf_0x131[0x3907]; // 0x131
	float m_flNextPrimaryAttack; // 0x3A38
	float m_flNextSecondaryAttack; // 0x3A3C
	char __buf_0x3A40[0x34]; // 0x3A40
	float m_flTimeWeaponIdle; // 0x3A74
 
}; // size=0x3A78
 
class DT_AttributeContainer
{
public:
 
	char __buf_0x00[0x28]; // 0x0
	int m_iReapplyProvisionParity; // 0x28
	unsigned long long m_hOuter; // 0x2C
	char m_ProviderType; // 0x34
	char __buf_0x35[0x2B]; // 0x35
	char m_Item; // 0x60
 
}; // size=0x61
 
class DT_ScriptCreatedItem
{
public:
 
	char __buf_0x00[0x268]; // 0x0
	int m_iItemDefinitionIndex; // 0x268
	int m_iEntityQuality; // 0x26C
	int m_iEntityLevel; // 0x270
	char __buf_0x274[0xC]; // 0x274
	int m_iItemIDHigh; // 0x280
	int m_iItemIDLow; // 0x284
	int m_iAccountID; // 0x288
	char __buf_0x28C[0xC]; // 0x28C
	unsigned char m_bInitialized; // 0x298
	char __buf_0x299[0x77]; // 0x299
	char m_NetworkedDynamicAttributesForDemos; // 0x310
	char __buf_0x311[0x2F]; // 0x311
	char m_szCustomName; // 0x340
 
}; // size=0x341
 
#pragma pack(pop)